/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomerInfoListInternalFrame.java
 *
 * Created on Mar 28, 2013, 8:35:15 PM
 */
package com.freebasicacc.ui;

import com.freebasicacc.ui.action.MainFrameAction;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author benzyaa
 */
public class CustomerInfoListInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form CustomerInfoListInternalFrame */
    private static CustomerInfoListInternalFrame customerInfoListInternalFrameInstance;
    
    private CustomerInfoListInternalFrame() {
        initComponents();
        this.SetIcon();
        this.setTitleFont();
    }
    
    private CustomerInfoListInternalFrame(JFrame mainFrame) {
        initComponents();
        this.SetIcon();
        this.getCustomerInFoListPanel1().setMainFrame(mainFrame);
        this.setTitleFont();
    }
    
    public static CustomerInfoListInternalFrame getCustomerInfoListInternalFrameInstance(JFrame mainFrame){
        if(customerInfoListInternalFrameInstance == null) customerInfoListInternalFrameInstance = new CustomerInfoListInternalFrame(mainFrame);
        return customerInfoListInternalFrameInstance;
    }
  
    
    private void SetIcon(){
        ImageIcon mainIcon = new ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/Office-Client-Male-Light-icon1616.png")); 
        this.setFrameIcon(mainIcon);
    }
    
    private void setTitleFont(){
        MainFrameAction action = new MainFrameAction();
        action.setInternalFramTitle(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerInFoListPanel1 = new com.freebasicacc.ui.CustomerInFoListPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setForeground(java.awt.Color.white);
        setMaximizable(true);
        setResizable(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/freebasicacc/ui/bundle"); // NOI18N
        setTitle(bundle.getString("list.customer")); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerInFoListPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(customerInFoListPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
    /*JScrollPane existScrollPane = this.customerInFoListPanel1.getjScrollPane1();
    JScrollPane scrollPane = (JScrollPane)ObjectUtil.deepCopy(existScrollPane);
    int customerListScrollPaneYPosition = scrollPane.getY();
    int customerListScrollPaneHeight = scrollPane.getHeight();
    int customerListScrollPaneYBottomPosition = customerListScrollPaneYPosition + customerListScrollPaneHeight;
    int componentHeight = this.getHeight();
    int additionalHeight = componentHeight-customerListScrollPaneYBottomPosition;
    scrollPane.setSize(scrollPane.getWidth(), (customerListScrollPaneHeight+additionalHeight)-40);
    //Dimension dimension = new Dimension();
    //dimension.setSize(200, 400);
    //scrollPane.setMaximumSize(dimension);
    //scrollPane.setPreferredSize(dimension);
    System.out.println("customerListTableXPosition=>"+customerListScrollPaneYPosition);
    System.out.println("componentHeight=>"+componentHeight);
    System.out.println("customerListScrollPaneHeight=>"+customerListScrollPaneHeight);
    this.customerInFoListPanel1.add(scrollPane);
    this.customerInFoListPanel1.remove(existScrollPane);
    scrollPane.setVisible(true);
    this.customerInFoListPanel1.validate();
    */
}//GEN-LAST:event_formComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.freebasicacc.ui.CustomerInFoListPanel customerInFoListPanel1;
    // End of variables declaration//GEN-END:variables


    /**
     * @return the customerInFoListPanel1
     */
    public com.freebasicacc.ui.CustomerInFoListPanel getCustomerInFoListPanel1() {
        return customerInFoListPanel1;
    }

    /**
     * @param customerInFoListPanel1 the customerInFoListPanel1 to set
     */
    public void setCustomerInFoListPanel1(com.freebasicacc.ui.CustomerInFoListPanel customerInFoListPanel1) {
        this.customerInFoListPanel1 = customerInFoListPanel1;
    }    
}
