/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomerInfoFormInternalFrame.java
 *
 * Created on Mar 27, 2013, 10:05:46 PM
 */
package com.freebasicacc.ui;

import com.freebasicacc.ui.action.MainFrameAction;
import javax.swing.ImageIcon;

/**
 *
 * @author benzyaa
 */
public class CustomerInfoFormInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form CustomerInfoFormInternalFrame */
    public CustomerInfoFormInternalFrame() {
        initComponents();
        this.SetIcon();
        this.setTitleFont();
    }
    
    public CustomerInfoFormInternalFrame(javax.swing.JPanel openerPanel) {
        initComponents();
        this.SetIcon();
        this.setTitleFont();
        this.customerInfoPanel2.setOpenerPanel(openerPanel);
        this.customerInfoPanel2.setInternalFrame(this);
    }
    
    private void SetIcon(){
        ImageIcon mainIcon = new ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/Office-Client-Male-Light-icon1616.png")); 
        this.setFrameIcon(mainIcon);
    }
    
    private void setTitleFont(){
        MainFrameAction action = new MainFrameAction();
        action.setInternalFramTitle(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerInfoPanel1 = new com.freebasicacc.ui.CustomerInfoPanel();
        customerInfoPanel2 = new com.freebasicacc.ui.CustomerInfoPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/freebasicacc/ui/bundle"); // NOI18N
        setTitle(bundle.getString("dialog.customer.title.add")); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(customerInfoPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(customerInfoPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.freebasicacc.ui.CustomerInfoPanel customerInfoPanel1;
    private com.freebasicacc.ui.CustomerInfoPanel customerInfoPanel2;
    // End of variables declaration//GEN-END:variables
}
