/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomerInfoFrame.java
 *
 * Created on Mar 26, 2013, 10:56:38 PM
 */
package com.freebasicacc.ui;

import com.freebasicacc.action.CustomerAction;
import com.freebasicacc.model.Customer;
import com.freebasicacc.ui.action.MainFrameAction;
import com.freebasicacc.ui.listener.BannedKeyListener;
import com.freebasicacc.ui.listener.LimitLengthListener;
import com.freebasicacc.util.DateUtil;
import javax.swing.JInternalFrame;

/**
 *
 * @author benzyaa
 */
public class CustomerInfoPanelEdit extends javax.swing.JPanel {

    /** Creates new form CustomerInfoFrame */
    public CustomerInfoPanelEdit() {
        initComponents();
         this.nameTextField.addKeyListener(new LimitLengthListener(50)); 
        this.contractTextField.addKeyListener(new LimitLengthListener(50));
        this.emailTextField.addKeyListener(new LimitLengthListener(300)); 
        this.addressTextArea.addKeyListener(new LimitLengthListener(300));
        this.remarkTextArea.addKeyListener(new LimitLengthListener(500));
        this.faxTextField.addKeyListener(new LimitLengthListener(14)); 
        this.phoneTextField.addKeyListener(new LimitLengthListener(14));
        this.faxTextField.addKeyListener(new BannedKeyListener("NUMBER"));
        this.phoneTextField.addKeyListener(new BannedKeyListener("NUMBER"));
        //assignDefaultValue(this.customer);
    }
    
    public void assignDefaultValue(Customer customer){
        this.getCustomerIdvalueLabel().setText(customer.getCustomerId());
        String registerDateStr =(customer.getRegisterDate() !=null)?DateUtil.convertDateUtilToDateStr(customer.getRegisterDate()) : "";
        String lastContractDateStr =(customer.getLastContractDate() !=null)?DateUtil.convertDateUtilToDateStr(customer.getLastContractDate()) : "";
        this.getCustomerRegisterDateValueLabel().setText(registerDateStr);
        this.getCustomerLastContractDateValueLabel().setText(lastContractDateStr);
        this.nameTextField.setText(customer.getCustomerName());
        this.contractTextField.setText(customer.getCustomerContract());
        this.phoneTextField.setText(customer.getCustomerPhone());
        this.faxTextField.setText(customer.getCustomerFax());
        this.emailTextField.setText(customer.getCustomerEmail());
        this.addressTextArea.setText(customer.getCustomerAddres());
        this.remarkTextArea.setText(customer.getRemark());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerHeaderLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        contractNameLabel = new javax.swing.JLabel();
        phoneNumLabel = new javax.swing.JLabel();
        faxLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        remarkLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarkTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        emailTextField = new javax.swing.JTextField();
        faxTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        contractTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        customerIdLabel = new javax.swing.JLabel();
        registerDateLabel = new javax.swing.JLabel();
        customerRegisterDateValueLabel = new javax.swing.JLabel();
        customerIdvalueLabel = new javax.swing.JLabel();
        lastContractDateLabel = new javax.swing.JLabel();
        customerLastContractDateValueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        customerHeaderLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customerHeaderLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/Office-Client-Male-Light-icon.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/freebasicacc/ui/bundle"); // NOI18N
        customerHeaderLabel.setText(bundle.getString("dialog.customer.info")); // NOI18N

        customerNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerNameLabel.setText(bundle.getString("customer.name")); // NOI18N

        addressLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addressLabel.setText(bundle.getString("customer.address")); // NOI18N

        contractNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contractNameLabel.setText(bundle.getString("customer.contract")); // NOI18N

        phoneNumLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        phoneNumLabel.setText(bundle.getString("customer.phone")); // NOI18N

        faxLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        faxLabel.setText(bundle.getString("customer.fax")); // NOI18N

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailLabel.setText(bundle.getString("customer.email")); // NOI18N

        remarkLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        remarkLabel.setText(bundle.getString("common.remark")); // NOI18N

        remarkTextArea.setColumns(20);
        remarkTextArea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        remarkTextArea.setRows(5);
        jScrollPane1.setViewportView(remarkTextArea);

        addressTextArea.setColumns(20);
        addressTextArea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addressTextArea.setRows(5);
        jScrollPane2.setViewportView(addressTextArea);

        emailTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        faxTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        phoneTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        contractTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        nameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/22.png"))); // NOI18N
        saveButton.setText(bundle.getString("common.save")); // NOI18N
        saveButton.setActionCommand(bundle.getString("common.save")); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/33.png"))); // NOI18N
        cancelButton.setText(bundle.getString("common.cancel")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/45.png"))); // NOI18N
        clearButton.setText(bundle.getString("common.reset")); // NOI18N
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        customerIdLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerIdLabel.setText(bundle.getString("customer.code")); // NOI18N

        registerDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        registerDateLabel.setText(bundle.getString("customer.registerdate")); // NOI18N

        customerRegisterDateValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerRegisterDateValueLabel.setText("jLabel3");

        customerIdvalueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerIdvalueLabel.setText("jLabel4");

        lastContractDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lastContractDateLabel.setText(bundle.getString("customer.lastcontractdate")); // NOI18N

        customerLastContractDateValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerLastContractDateValueLabel.setText("jLabel6");

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(contractNameLabel)
                            .addComponent(emailLabel)
                            .addComponent(addressLabel)
                            .addComponent(remarkLabel)
                            .addComponent(customerNameLabel)
                            .addComponent(customerIdLabel)
                            .addComponent(lastContractDateLabel)
                            .addComponent(registerDateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerLastContractDateValueLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(saveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(customerIdvalueLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(contractTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(phoneNumLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(faxLabel)))))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(faxTextField)
                                    .addComponent(phoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                                    .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(customerRegisterDateValueLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(customerHeaderLabel)))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(customerHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIdvalueLabel)
                    .addComponent(customerIdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerRegisterDateValueLabel)
                    .addComponent(registerDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastContractDateLabel)
                    .addComponent(customerLastContractDateValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNameLabel)
                    .addComponent(jLabel1)
                    .addComponent(phoneNumLabel)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractNameLabel)
                    .addComponent(contractTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(faxLabel)
                    .addComponent(faxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remarkLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton)
                            .addComponent(clearButton)
                            .addComponent(cancelButton)))
                    .addComponent(jLabel5))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_emailTextFieldActionPerformed

private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    CustomerAction action = new CustomerAction();
    action.updateCustomerAction(this);
    //action.saveCustomerAction(this);
}//GEN-LAST:event_saveButtonActionPerformed

private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
    this.assignDefaultValue(customer);
}//GEN-LAST:event_clearButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    MainFrameAction action = new MainFrameAction();
    action.closeInternalFrame(getInternalFrame());
}//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel contractNameLabel;
    private javax.swing.JTextField contractTextField;
    private javax.swing.JLabel customerHeaderLabel;
    private javax.swing.JLabel customerIdLabel;
    private javax.swing.JLabel customerIdvalueLabel;
    private javax.swing.JLabel customerLastContractDateValueLabel;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JLabel customerRegisterDateValueLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel faxLabel;
    private javax.swing.JTextField faxTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastContractDateLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel phoneNumLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel registerDateLabel;
    private javax.swing.JLabel remarkLabel;
    private javax.swing.JTextArea remarkTextArea;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JPanel openerPanel; 
    private Customer customer;
    private JInternalFrame internalFrame;
    /**
     * @return the addressLabel
     */
    public javax.swing.JLabel getAddressLabel() {
        return addressLabel;
    }

    /**
     * @return the addressTextArea
     */
    public javax.swing.JTextArea getAddressTextArea() {
        return addressTextArea;
    }

    /**
     * @return the cancelButton
     */
    public javax.swing.JButton getCancelButton() {
        return cancelButton;
    }

    /**
     * @return the clearButton
     */
    public javax.swing.JButton getClearButton() {
        return clearButton;
    }

    /**
     * @return the contractNameLabel
     */
    public javax.swing.JLabel getContractNameLabel() {
        return contractNameLabel;
    }

    /**
     * @return the contractTextField
     */
    public javax.swing.JTextField getContractTextField() {
        return contractTextField;
    }

    /**
     * @return the customerHeaderLabel
     */
    public javax.swing.JLabel getCustomerHeaderLabel() {
        return customerHeaderLabel;
    }

    /**
     * @return the customerNameLabel
     */
    public javax.swing.JLabel getCustomerNameLabel() {
        return customerNameLabel;
    }

    /**
     * @return the emailLabel
     */
    public javax.swing.JLabel getEmailLabel() {
        return emailLabel;
    }

    /**
     * @return the emailTextField
     */
    public javax.swing.JTextField getEmailTextField() {
        return emailTextField;
    }

    /**
     * @return the faxLabel
     */
    public javax.swing.JLabel getFaxLabel() {
        return faxLabel;
    }

    /**
     * @return the faxTextField
     */
    public javax.swing.JTextField getFaxTextField() {
        return faxTextField;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @return the jScrollPane2
     */
    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * @return the nameTextField
     */
    public javax.swing.JTextField getNameTextField() {
        return nameTextField;
    }

    /**
     * @return the phoneNumLabel
     */
    public javax.swing.JLabel getPhoneNumLabel() {
        return phoneNumLabel;
    }

    /**
     * @return the phoneTextField
     */
    public javax.swing.JTextField getPhoneTextField() {
        return phoneTextField;
    }

    /**
     * @return the remarkLabel
     */
    public javax.swing.JLabel getRemarkLabel() {
        return remarkLabel;
    }

    /**
     * @return the remarkTextArea
     */
    public javax.swing.JTextArea getRemarkTextArea() {
        return remarkTextArea;
    }

    /**
     * @return the saveButton
     */
    public javax.swing.JButton getSaveButton() {
        return saveButton;
    }

    /**
     * @return the openerPanel
     */
    public javax.swing.JPanel getOpenerPanel() {
        return openerPanel;
    }

    /**
     * @param openerPanel the openerPanel to set
     */
    public void setOpenerPanel(javax.swing.JPanel openerPanel) {
        this.openerPanel = openerPanel;
    }

    /**
     * @return the customer
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * @param customer the customer to set
     */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /**
     * @param contractNameLabel the contractNameLabel to set
     */
    public void setContractNameLabel(javax.swing.JLabel contractNameLabel) {
        this.contractNameLabel = contractNameLabel;
    }

    /**
     * @return the customerIdvalueLabel
     */
    public javax.swing.JLabel getCustomerIdvalueLabel() {
        return customerIdvalueLabel;
    }

    /**
     * @return the customerLastContractDateValueLabel
     */
    public javax.swing.JLabel getCustomerLastContractDateValueLabel() {
        return customerLastContractDateValueLabel;
    }

    /**
     * @return the customerRegisterDateValueLabel
     */
    public javax.swing.JLabel getCustomerRegisterDateValueLabel() {
        return customerRegisterDateValueLabel;
    }

    /**
     * @return the internalFrame
     */
    public JInternalFrame getInternalFrame() {
        return internalFrame;
    }

    /**
     * @param internalFrame the internalFrame to set
     */
    public void setInternalFrame(JInternalFrame internalFrame) {
        this.internalFrame = internalFrame;
    }
    
    
}
