/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QuotationInfoPanel.java
 *
 * Created on Apr 6, 2013, 10:45:15 AM
 */
package com.freebasicacc.ui;

import com.freebasicacc.action.InvoiceAction;
import com.freebasicacc.ui.action.MainFrameAction;
import com.freebasicacc.ui.listener.BannedKeyListener;
import com.freebasicacc.ui.listener.InvoiceDetailListTableListener;
import com.freebasicacc.ui.listener.LimitLengthListener;
import com.freebasicacc.util.DateUtil;
import com.freebasicacc.util.MessageUtil;
import com.freebasicacc.util.UIUtil;
import javax.swing.JInternalFrame;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author benzyaa
 */
public class InvoiceInfoPanel extends javax.swing.JPanel {

    /** Creates new form QuotationInfoPanel */
    public InvoiceInfoPanel() {
        initComponents();
        InvoiceDetailListTableListener tableListener = new InvoiceDetailListTableListener();
        tableListener.setHandlerPanel(this);
        this.invoiceDateTextField.setText(DateUtil.convertDateUtilToDateStr(new java.util.Date()));
        this.invoiceDetailTable.getModel().addTableModelListener(tableListener);
        this.invoiceDetailTable.getTableHeader().setFont(new java.awt.Font("Tahoma", 0, 12));
        this.invoiceDateTextField.addKeyListener(new BannedKeyListener("DATE"));
        this.paymentDueDateTextField.addKeyListener(new BannedKeyListener("DATE"));
        this.invoiceDateTextField.addKeyListener(new LimitLengthListener(10));
        this.paymentDueDateTextField.addKeyListener(new LimitLengthListener(10));
        this.poNumberTextField.addKeyListener(new LimitLengthListener(10));
    }
    
      public javax.swing.table.DefaultTableModel generateModelForColumn(){
        return new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                    MessageUtil.getMessage("common.sequence"), 
                    MessageUtil.getMessage("material.code"),
                    MessageUtil.getMessage("common.detail"),
                    MessageUtil.getMessage("common.quantity"),
                    MessageUtil.getMessage("invoice.materialunit"),   
                    MessageUtil.getMessage("invoice.priceperunit"),
                    MessageUtil.getMessage("invoice.totalvalue"),
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invoiceInfoTitleLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        customerDialogOpenButton = new javax.swing.JButton();
        addDetailButton = new javax.swing.JButton();
        removeDetailButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceDetailTable = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        totalValueTextField = new javax.swing.JTextField();
        vatTextField = new javax.swing.JTextField();
        netValueTextField = new javax.swing.JTextField();
        totalValueLabel = new javax.swing.JLabel();
        vatLabel = new javax.swing.JLabel();
        netValueLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        addressLabel = new javax.swing.JLabel();
        customerIdLabel = new javax.swing.JLabel();
        customerIdTextField = new javax.swing.JTextField();
        invoiceDateLabel = new javax.swing.JLabel();
        poNumberLabel = new javax.swing.JLabel();
        paymentDueDateLabel = new javax.swing.JLabel();
        poNumberTextField = new javax.swing.JTextField();
        paymentDueDateTextField = new javax.swing.JTextField();
        paymentDueDatePicker = new javax.swing.JButton();
        invoiceDueDateLabel = new javax.swing.JLabel();
        invoiceDueDateTextField = new javax.swing.JTextField();
        invoiceDueDatePicker = new javax.swing.JButton();
        discountLabel = new javax.swing.JLabel();
        discountTextField = new javax.swing.JTextField();
        invoiceDateTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        invoiceInfoTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        invoiceInfoTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/Document.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/freebasicacc/ui/bundle"); // NOI18N
        invoiceInfoTitleLabel.setText(bundle.getString("dialog.invoice.title.create")); // NOI18N

        customerNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerNameLabel.setText(bundle.getString("invoice.company")); // NOI18N

        customerNameTextField.setEditable(false);
        customerNameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTextFieldActionPerformed(evt);
            }
        });

        customerDialogOpenButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerDialogOpenButton.setText("...");
        customerDialogOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerDialogOpenButtonActionPerformed(evt);
            }
        });

        addDetailButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addDetailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/13.png"))); // NOI18N
        addDetailButton.setText(bundle.getString("common.addshort")); // NOI18N
        addDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDetailButtonActionPerformed(evt);
            }
        });

        removeDetailButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        removeDetailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/14.png"))); // NOI18N
        removeDetailButton.setText(bundle.getString("common.remove")); // NOI18N
        removeDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDetailButtonActionPerformed(evt);
            }
        });

        invoiceDetailTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        invoiceDetailTable.setModel(this.generateModelForColumn());
        invoiceDetailTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                invoiceDetailTableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                invoiceDetailTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(invoiceDetailTable);

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/22.png"))); // NOI18N
        saveButton.setText(bundle.getString("common.save")); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/45.png"))); // NOI18N
        clearButton.setText(bundle.getString("common.reset")); // NOI18N
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/33.png"))); // NOI18N
        cancelButton.setText(bundle.getString("common.cancel")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        totalValueTextField.setEditable(false);
        totalValueTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalValueTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalValueTextField.setText("0.00");
        totalValueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalValueTextFieldActionPerformed(evt);
            }
        });

        vatTextField.setEditable(false);
        vatTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vatTextField.setText("0.00");
        vatTextField.setToolTipText("");
        vatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vatTextFieldActionPerformed(evt);
            }
        });

        netValueTextField.setEditable(false);
        netValueTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        netValueTextField.setText("0.00");
        netValueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netValueTextFieldActionPerformed(evt);
            }
        });

        totalValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalValueLabel.setText(bundle.getString("invoice.totalvalue")); // NOI18N

        vatLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vatLabel.setText(bundle.getString("invoice.tax")); // NOI18N

        netValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        netValueLabel.setText(bundle.getString("invoice.netvalue")); // NOI18N

        addressTextArea.setColumns(20);
        addressTextArea.setEditable(false);
        addressTextArea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addressTextArea.setRows(5);
        jScrollPane2.setViewportView(addressTextArea);

        addressLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addressLabel.setText(bundle.getString("customer.address")); // NOI18N

        customerIdLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerIdLabel.setText(bundle.getString("invoice.customercode")); // NOI18N

        customerIdTextField.setEditable(false);
        customerIdTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        invoiceDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        invoiceDateLabel.setText(bundle.getString("common.date")); // NOI18N

        poNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        poNumberLabel.setText(bundle.getString("invoice.ponumber")); // NOI18N

        paymentDueDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paymentDueDateLabel.setText(bundle.getString("invoice.paymentduedate")); // NOI18N

        poNumberTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        paymentDueDateTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        paymentDueDatePicker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/43.png"))); // NOI18N
        paymentDueDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentDueDatePickerActionPerformed(evt);
            }
        });

        invoiceDueDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        invoiceDueDateLabel.setText(bundle.getString("invoice.duedate")); // NOI18N

        invoiceDueDateTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        invoiceDueDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceDueDateTextFieldActionPerformed(evt);
            }
        });

        invoiceDueDatePicker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/43.png"))); // NOI18N
        invoiceDueDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceDueDatePickerActionPerformed(evt);
            }
        });

        discountLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        discountLabel.setText(bundle.getString("invoice.discount")); // NOI18N

        discountTextField.setEditable(false);
        discountTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        discountTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        discountTextField.setText("0.00");
        discountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTextFieldActionPerformed(evt);
            }
        });

        invoiceDateTextField.setEditable(false);
        invoiceDateTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(addressLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paymentDueDateLabel)
                            .addComponent(invoiceDueDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paymentDueDateTextField)
                            .addComponent(invoiceDueDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(poNumberLabel)
                            .addComponent(invoiceDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(invoiceDateTextField)
                            .addComponent(poNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paymentDueDatePicker, 0, 0, Short.MAX_VALUE)
                    .addComponent(invoiceDueDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(invoiceInfoTitleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(customerNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerDialogOpenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(customerIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addDetailButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeDetailButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(netValueLabel)
                                    .addComponent(discountLabel)
                                    .addComponent(totalValueLabel)
                                    .addComponent(vatLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(netValueTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vatTextField)
                                    .addComponent(discountTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(totalValueTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invoiceInfoTitleLabel)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceDateLabel)
                            .addComponent(invoiceDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(poNumberLabel)
                            .addComponent(poNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(paymentDueDateLabel)
                                .addComponent(paymentDueDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(paymentDueDatePicker)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(invoiceDueDatePicker)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(invoiceDueDateLabel)
                                .addComponent(invoiceDueDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerNameLabel)
                            .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerDialogOpenButton)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressLabel))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerIdLabel)
                            .addComponent(customerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addDetailButton)
                            .addComponent(removeDetailButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalValueLabel))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vatLabel)
                    .addComponent(vatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netValueLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(clearButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void customerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_customerNameTextFieldActionPerformed

private void customerDialogOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerDialogOpenButtonActionPerformed
    MainFrameAction action = new MainFrameAction();
    JMenuItem menuItem = new JMenuItem();
    menuItem.setName("CUSTOMER_DIALOG_MENU_ITEM");
    action.openInternalFormByType((MainFrame)this.getMainFrame(), menuItem,this,null);
}//GEN-LAST:event_customerDialogOpenButtonActionPerformed

private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
   assignDefaultValue();
}//GEN-LAST:event_clearButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
     MainFrameAction action = new MainFrameAction();
     action.closeInternalFrame(this.getInternalFrame());
}//GEN-LAST:event_cancelButtonActionPerformed

private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    InvoiceAction action = new InvoiceAction();
    action.saveInvoiceAction(this);
}//GEN-LAST:event_saveButtonActionPerformed

private void removeDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDetailButtonActionPerformed
    InvoiceAction action = new InvoiceAction();
    action.removeInvoiceDetailRow(this);
}//GEN-LAST:event_removeDetailButtonActionPerformed

private void addDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDetailButtonActionPerformed
        MainFrameAction action = new MainFrameAction();
        JMenuItem menuItem = new JMenuItem();
        menuItem.setName("MATERIAL_DIALOG_MENU_ITEM");
        action.openInternalFormByType((MainFrame)this.getMainFrame(), menuItem, this, null);
}//GEN-LAST:event_addDetailButtonActionPerformed

private void invoiceDetailTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invoiceDetailTableKeyReleased
 
}//GEN-LAST:event_invoiceDetailTableKeyReleased

private void invoiceDetailTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invoiceDetailTableKeyPressed
 
}//GEN-LAST:event_invoiceDetailTableKeyPressed

private void paymentDueDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentDueDatePickerActionPerformed
            UIUtil util = new UIUtil();
            util.openDatepickerForTextField(this.paymentDueDateTextField,this.getMainFrame());
}//GEN-LAST:event_paymentDueDatePickerActionPerformed

private void invoiceDueDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceDueDateTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_invoiceDueDateTextFieldActionPerformed

private void totalValueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalValueTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_totalValueTextFieldActionPerformed

private void vatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_vatTextFieldActionPerformed

private void discountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_discountTextFieldActionPerformed

private void invoiceDueDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceDueDatePickerActionPerformed
        UIUtil util = new UIUtil();
        util.openDatepickerForTextField(this.invoiceDueDateTextField,this.getMainFrame());
}//GEN-LAST:event_invoiceDueDatePickerActionPerformed

private void netValueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netValueTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_netValueTextFieldActionPerformed

 public void assignDefaultValue(){
        this.getCustomerIdTextField().setText("");
        this.getCustomerNameTextField().setText("");
        this.getAddressTextArea().setText("");
        this.getInvoiceDateTextField().setText("");
        this.getPoNumberTextField().setText("");
        this.getPaymentDueDateTextField().setText("");
        this.getInvoiceDueDateTextField().setText("");
        this.getTotalValueTextField().setText("0.00");
        this.getVatTextField().setText("0.00");
        this.getNetValueTextField().setText("0.00");
        InvoiceAction action = new InvoiceAction();
        action.removeInvoiceDetailAllRow(this);
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton addDetailButton;
    protected javax.swing.JLabel addressLabel;
    protected javax.swing.JTextArea addressTextArea;
    protected javax.swing.JButton cancelButton;
    protected javax.swing.JButton clearButton;
    protected javax.swing.JButton customerDialogOpenButton;
    protected javax.swing.JLabel customerIdLabel;
    protected javax.swing.JTextField customerIdTextField;
    protected javax.swing.JLabel customerNameLabel;
    protected javax.swing.JTextField customerNameTextField;
    protected javax.swing.JLabel discountLabel;
    protected javax.swing.JTextField discountTextField;
    protected javax.swing.JLabel invoiceDateLabel;
    protected javax.swing.JTextField invoiceDateTextField;
    protected javax.swing.JTable invoiceDetailTable;
    protected javax.swing.JLabel invoiceDueDateLabel;
    protected javax.swing.JButton invoiceDueDatePicker;
    protected javax.swing.JTextField invoiceDueDateTextField;
    protected javax.swing.JLabel invoiceInfoTitleLabel;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JScrollPane jScrollPane2;
    protected javax.swing.JLabel netValueLabel;
    protected javax.swing.JTextField netValueTextField;
    protected javax.swing.JLabel paymentDueDateLabel;
    protected javax.swing.JButton paymentDueDatePicker;
    protected javax.swing.JTextField paymentDueDateTextField;
    protected javax.swing.JLabel poNumberLabel;
    protected javax.swing.JTextField poNumberTextField;
    protected javax.swing.JButton removeDetailButton;
    protected javax.swing.JButton saveButton;
    protected javax.swing.JLabel totalValueLabel;
    protected javax.swing.JTextField totalValueTextField;
    protected javax.swing.JLabel vatLabel;
    protected javax.swing.JTextField vatTextField;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JFrame mainFrame;
    private JPanel openerPanel;
    private JInternalFrame internalFrame;

    /**
     * @return the addDetailButton
     */
    public javax.swing.JButton getAddDetailButton() {
        return addDetailButton;
    }

    /**
     * @param addDetailButton the addDetailButton to set
     */
    public void setAddDetailButton(javax.swing.JButton addDetailButton) {
        this.addDetailButton = addDetailButton;
    }

    /**
     * @return the addressLabel
     */
    public javax.swing.JLabel getAddressLabel() {
        return addressLabel;
    }

    /**
     * @param addressLabel the addressLabel to set
     */
    public void setAddressLabel(javax.swing.JLabel addressLabel) {
        this.addressLabel = addressLabel;
    }

    /**
     * @return the addressTextArea
     */
    public javax.swing.JTextArea getAddressTextArea() {
        return addressTextArea;
    }

    /**
     * @param addressTextArea the addressTextArea to set
     */
    public void setAddressTextArea(javax.swing.JTextArea addressTextArea) {
        this.addressTextArea = addressTextArea;
    }

    /**
     * @return the cancelButton
     */
    public javax.swing.JButton getCancelButton() {
        return cancelButton;
    }

    /**
     * @param cancelButton the cancelButton to set
     */
    public void setCancelButton(javax.swing.JButton cancelButton) {
        this.cancelButton = cancelButton;
    }

    /**
     * @return the clearButton
     */
    public javax.swing.JButton getClearButton() {
        return clearButton;
    }

    /**
     * @param clearButton the clearButton to set
     */
    public void setClearButton(javax.swing.JButton clearButton) {
        this.clearButton = clearButton;
    }

    /**
     * @return the customerDialogOpenButton
     */
    public javax.swing.JButton getCustomerDialogOpenButton() {
        return customerDialogOpenButton;
    }

    /**
     * @param customerDialogOpenButton the customerDialogOpenButton to set
     */
    public void setCustomerDialogOpenButton(javax.swing.JButton customerDialogOpenButton) {
        this.customerDialogOpenButton = customerDialogOpenButton;
    }

    /**
     * @return the customerIdLabel
     */
    public javax.swing.JLabel getCustomerIdLabel() {
        return customerIdLabel;
    }

    /**
     * @param customerIdLabel the customerIdLabel to set
     */
    public void setCustomerIdLabel(javax.swing.JLabel customerIdLabel) {
        this.customerIdLabel = customerIdLabel;
    }

    /**
     * @return the customerIdTextField
     */
    public javax.swing.JTextField getCustomerIdTextField() {
        return customerIdTextField;
    }

    /**
     * @param customerIdTextField the customerIdTextField to set
     */
    public void setCustomerIdTextField(javax.swing.JTextField customerIdTextField) {
        this.customerIdTextField = customerIdTextField;
    }

    /**
     * @return the customerNameLabel
     */
    public javax.swing.JLabel getCustomerNameLabel() {
        return customerNameLabel;
    }

    /**
     * @param customerNameLabel the customerNameLabel to set
     */
    public void setCustomerNameLabel(javax.swing.JLabel customerNameLabel) {
        this.customerNameLabel = customerNameLabel;
    }

    /**
     * @return the customerNameTextField
     */
    public javax.swing.JTextField getCustomerNameTextField() {
        return customerNameTextField;
    }

    /**
     * @param customerNameTextField the customerNameTextField to set
     */
    public void setCustomerNameTextField(javax.swing.JTextField customerNameTextField) {
        this.customerNameTextField = customerNameTextField;
    }

    /**
     * @return the discountLabel
     */
    public javax.swing.JLabel getDiscountLabel() {
        return discountLabel;
    }

    /**
     * @param discountLabel the discountLabel to set
     */
    public void setDiscountLabel(javax.swing.JLabel discountLabel) {
        this.discountLabel = discountLabel;
    }

    /**
     * @return the discountTextField
     */
    public javax.swing.JTextField getDiscountTextField() {
        return discountTextField;
    }

    /**
     * @param discountTextField the discountTextField to set
     */
    public void setDiscountTextField(javax.swing.JTextField discountTextField) {
        this.discountTextField = discountTextField;
    }

    /**
     * @return the invoiceDateLabel
     */
    public javax.swing.JLabel getInvoiceDateLabel() {
        return invoiceDateLabel;
    }

    /**
     * @param invoiceDateLabel the invoiceDateLabel to set
     */
    public void setInvoiceDateLabel(javax.swing.JLabel invoiceDateLabel) {
        this.invoiceDateLabel = invoiceDateLabel;
    }

    /**
     * @return the invoiceDateTextField
     */
    public javax.swing.JTextField getInvoiceDateTextField() {
        return invoiceDateTextField;
    }

    /**
     * @param invoiceDateTextField the invoiceDateTextField to set
     */
    public void setInvoiceDateTextField(javax.swing.JTextField invoiceDateTextField) {
        this.invoiceDateTextField = invoiceDateTextField;
    }

    /**
     * @return the invoiceDetailTable
     */
    public javax.swing.JTable getInvoiceDetailTable() {
        return invoiceDetailTable;
    }

    /**
     * @param invoiceDetailTable the invoiceDetailTable to set
     */
    public void setInvoiceDetailTable(javax.swing.JTable invoiceDetailTable) {
        this.invoiceDetailTable = invoiceDetailTable;
    }

    /**
     * @return the invoiceDueDateLabel
     */
    public javax.swing.JLabel getInvoiceDueDateLabel() {
        return invoiceDueDateLabel;
    }

    /**
     * @param invoiceDueDateLabel the invoiceDueDateLabel to set
     */
    public void setInvoiceDueDateLabel(javax.swing.JLabel invoiceDueDateLabel) {
        this.invoiceDueDateLabel = invoiceDueDateLabel;
    }

    /**
     * @return the invoiceDueDateTextField
     */
    public javax.swing.JTextField getInvoiceDueDateTextField() {
        return invoiceDueDateTextField;
    }

    /**
     * @param invoiceDueDateTextField the invoiceDueDateTextField to set
     */
    public void setInvoiceDueDateTextField(javax.swing.JTextField invoiceDueDateTextField) {
        this.invoiceDueDateTextField = invoiceDueDateTextField;
    }

    /**
     * @return the invoiceInfoTitleLabel
     */
    public javax.swing.JLabel getInvoiceInfoTitleLabel() {
        return invoiceInfoTitleLabel;
    }

    /**
     * @param invoiceInfoTitleLabel the invoiceInfoTitleLabel to set
     */
    public void setInvoiceInfoTitleLabel(javax.swing.JLabel invoiceInfoTitleLabel) {
        this.invoiceInfoTitleLabel = invoiceInfoTitleLabel;
    }

    /**
     * @return the jButton1
     */
    public javax.swing.JButton getjButton1() {
        return paymentDueDatePicker;
    }

    /**
     * @param jButton1 the jButton1 to set
     */
    public void setjButton1(javax.swing.JButton jButton1) {
        this.paymentDueDatePicker = jButton1;
    }

    /**
     * @return the jButton2
     */
    public javax.swing.JButton getjButton2() {
        return invoiceDueDatePicker;
    }

    /**
     * @param jButton2 the jButton2 to set
     */
    public void setjButton2(javax.swing.JButton jButton2) {
        this.invoiceDueDatePicker = jButton2;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jScrollPane2
     */
    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * @param jScrollPane2 the jScrollPane2 to set
     */
    public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    /**
     * @return the netValueLabel
     */
    public javax.swing.JLabel getNetValueLabel() {
        return netValueLabel;
    }

    /**
     * @param netValueLabel the netValueLabel to set
     */
    public void setNetValueLabel(javax.swing.JLabel netValueLabel) {
        this.netValueLabel = netValueLabel;
    }

    /**
     * @return the netValueTextField
     */
    public javax.swing.JTextField getNetValueTextField() {
        return netValueTextField;
    }

    /**
     * @param netValueTextField the netValueTextField to set
     */
    public void setNetValueTextField(javax.swing.JTextField netValueTextField) {
        this.netValueTextField = netValueTextField;
    }

    /**
     * @return the netValueTextLabel
     */
   
    /**
     * @return the paymentDueDateLabel
     */
    public javax.swing.JLabel getPaymentDueDateLabel() {
        return paymentDueDateLabel;
    }

    /**
     * @param paymentDueDateLabel the paymentDueDateLabel to set
     */
    public void setPaymentDueDateLabel(javax.swing.JLabel paymentDueDateLabel) {
        this.paymentDueDateLabel = paymentDueDateLabel;
    }

    /**
     * @return the paymentDueDateTextField
     */
    public javax.swing.JTextField getPaymentDueDateTextField() {
        return paymentDueDateTextField;
    }

    /**
     * @param paymentDueDateTextField the paymentDueDateTextField to set
     */
    public void setPaymentDueDateTextField(javax.swing.JTextField paymentDueDateTextField) {
        this.paymentDueDateTextField = paymentDueDateTextField;
    }

    /**
     * @return the poNumberLabel
     */
    public javax.swing.JLabel getPoNumberLabel() {
        return poNumberLabel;
    }

    /**
     * @param poNumberLabel the poNumberLabel to set
     */
    public void setPoNumberLabel(javax.swing.JLabel poNumberLabel) {
        this.poNumberLabel = poNumberLabel;
    }

    /**
     * @return the poNumberTextField
     */
    public javax.swing.JTextField getPoNumberTextField() {
        return poNumberTextField;
    }

    /**
     * @param poNumberTextField the poNumberTextField to set
     */
    public void setPoNumberTextField(javax.swing.JTextField poNumberTextField) {
        this.poNumberTextField = poNumberTextField;
    }

    /**
     * @return the removeDetailButton
     */
    public javax.swing.JButton getRemoveDetailButton() {
        return removeDetailButton;
    }

    /**
     * @param removeDetailButton the removeDetailButton to set
     */
    public void setRemoveDetailButton(javax.swing.JButton removeDetailButton) {
        this.removeDetailButton = removeDetailButton;
    }

    /**
     * @return the saveButton
     */
    public javax.swing.JButton getSaveButton() {
        return saveButton;
    }

    /**
     * @param saveButton the saveButton to set
     */
    public void setSaveButton(javax.swing.JButton saveButton) {
        this.saveButton = saveButton;
    }

    /**
     * @return the totalValueLabel
     */
    public javax.swing.JLabel getTotalValueLabel() {
        return totalValueLabel;
    }

    /**
     * @param totalValueLabel the totalValueLabel to set
     */
    public void setTotalValueLabel(javax.swing.JLabel totalValueLabel) {
        this.totalValueLabel = totalValueLabel;
    }

    /**
     * @return the totalValueTextField
     */
    public javax.swing.JTextField getTotalValueTextField() {
        return totalValueTextField;
    }

    /**
     * @param totalValueTextField the totalValueTextField to set
     */
    public void setTotalValueTextField(javax.swing.JTextField totalValueTextField) {
        this.totalValueTextField = totalValueTextField;
    }

    /**
     * @return the vatLabel
     */
    public javax.swing.JLabel getVatLabel() {
        return vatLabel;
    }

    /**
     * @param vatLabel the vatLabel to set
     */
    public void setVatLabel(javax.swing.JLabel vatLabel) {
        this.vatLabel = vatLabel;
    }

    /**
     * @return the vatTextField
     */
    public javax.swing.JTextField getVatTextField() {
        return vatTextField;
    }

    /**
     * @param vatTextField the vatTextField to set
     */
    public void setVatTextField(javax.swing.JTextField vatTextField) {
        this.vatTextField = vatTextField;
    }

    /**
     * @return the mainFrame
     */
    public javax.swing.JFrame getMainFrame() {
        return mainFrame;
    }

    /**
     * @param mainFrame the mainFrame to set
     */
    public void setMainFrame(javax.swing.JFrame mainFrame) {
        this.mainFrame = mainFrame;
    }

    /**
     * @return the openerPanel
     */
    public JPanel getOpenerPanel() {
        return openerPanel;
    }

    /**
     * @param openerPanel the openerPanel to set
     */
    public void setOpenerPanel(JPanel openerPanel) {
        this.openerPanel = openerPanel;
    }

    /**
     * @return the internalFrame
     */
    public JInternalFrame getInternalFrame() {
        return internalFrame;
    }

    /**
     * @param internalFrame the internalFrame to set
     */
    public void setInternalFrame(JInternalFrame internalFrame) {
        this.internalFrame = internalFrame;
    }
}