/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QuotationInfoPanel.java
 *
 * Created on Apr 6, 2013, 10:45:15 AM
 */
package com.freebasicacc.ui;

import com.freebasicacc.action.InvoiceAction;
import com.freebasicacc.model.InvoiceDetail;
import com.freebasicacc.model.InvoiceHead;
import com.freebasicacc.ui.action.MainFrameAction;
import com.freebasicacc.util.DateUtil;
import com.freebasicacc.util.MessageUtil;
import com.freebasicacc.util.StringUtil;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author benzyaa
 */
public class InvoiceInfoPanelView extends javax.swing.JPanel {

    /** Creates new form QuotationInfoPanel */
    public InvoiceInfoPanelView() {
        initComponents();
        this.invoiceDetailTable.getTableHeader().setFont(new java.awt.Font("Tahoma", 0, 12));
    }
    
        public javax.swing.table.DefaultTableModel generateModelForColumn(){
        return new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                    MessageUtil.getMessage("common.sequence"), 
                    MessageUtil.getMessage("material.code"),
                    MessageUtil.getMessage("common.detail"),
                    MessageUtil.getMessage("common.quantity"),
                    MessageUtil.getMessage("invoice.materialunit"),   
                    MessageUtil.getMessage("invoice.priceperunit"),
                    MessageUtil.getMessage("invoice.totalvalue"),
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        invoiceInfoTitleLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceDetailTable = new javax.swing.JTable();
        cancelButton = new javax.swing.JButton();
        totalValueTextField = new javax.swing.JTextField();
        vatTextField = new javax.swing.JTextField();
        netValueTextField = new javax.swing.JTextField();
        totalValueLabel = new javax.swing.JLabel();
        vatLabel = new javax.swing.JLabel();
        netValueLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        addressLabel = new javax.swing.JLabel();
        customerIdLabel = new javax.swing.JLabel();
        customerIdTextField = new javax.swing.JTextField();
        invoiceDateLabel = new javax.swing.JLabel();
        poNumberLabel = new javax.swing.JLabel();
        paymentDueDateLabel = new javax.swing.JLabel();
        poNumberTextField = new javax.swing.JTextField();
        paymentDueDateTextField = new javax.swing.JTextField();
        invoiceDueDateLabel = new javax.swing.JLabel();
        invoiceDueDateTextField = new javax.swing.JTextField();
        discountLabel = new javax.swing.JLabel();
        discountTextField = new javax.swing.JTextField();
        netValueTextLabel = new javax.swing.JLabel();
        invoiceDateTextField = new javax.swing.JTextField();
        netValueTextTextField = new javax.swing.JTextField();
        invoiceIdLabel = new javax.swing.JLabel();
        invoiceIdTextField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(886, 740));

        invoiceInfoTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        invoiceInfoTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/Document.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/freebasicacc/ui/bundle"); // NOI18N
        invoiceInfoTitleLabel.setText(bundle.getString("dialog.invoice.title.info")); // NOI18N

        customerNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerNameLabel.setText(bundle.getString("invoice.company")); // NOI18N

        customerNameTextField.setEditable(false);
        customerNameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTextFieldActionPerformed(evt);
            }
        });

        invoiceDetailTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        invoiceDetailTable.setModel(this.generateModelForColumn());
        invoiceDetailTable.setEnabled(false);
        invoiceDetailTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                invoiceDetailTableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                invoiceDetailTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(invoiceDetailTable);

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/33.png"))); // NOI18N
        cancelButton.setText(bundle.getString("common.close")); // NOI18N
        cancelButton.setAlignmentY(0.0F);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        totalValueTextField.setEditable(false);
        totalValueTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalValueTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalValueTextField.setText("0");
        totalValueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalValueTextFieldActionPerformed(evt);
            }
        });

        vatTextField.setEditable(false);
        vatTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vatTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vatTextField.setText("0");
        vatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vatTextFieldActionPerformed(evt);
            }
        });

        netValueTextField.setEditable(false);
        netValueTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        netValueTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        netValueTextField.setText("0");

        totalValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalValueLabel.setText(bundle.getString("invoice.totalvalue")); // NOI18N

        vatLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vatLabel.setText(bundle.getString("invoice.tax")); // NOI18N

        netValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        netValueLabel.setText(bundle.getString("invoice.netvalue")); // NOI18N

        addressTextArea.setColumns(20);
        addressTextArea.setEditable(false);
        addressTextArea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addressTextArea.setRows(5);
        jScrollPane2.setViewportView(addressTextArea);

        addressLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addressLabel.setText(bundle.getString("customer.address")); // NOI18N

        customerIdLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerIdLabel.setText(bundle.getString("invoice.customercode")); // NOI18N

        customerIdTextField.setEditable(false);
        customerIdTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        invoiceDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        invoiceDateLabel.setText(bundle.getString("common.date")); // NOI18N

        poNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        poNumberLabel.setText(bundle.getString("invoice.ponumber")); // NOI18N

        paymentDueDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paymentDueDateLabel.setText(bundle.getString("invoice.paymentduedate")); // NOI18N

        poNumberTextField.setEditable(false);

        paymentDueDateTextField.setEditable(false);
        paymentDueDateTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paymentDueDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentDueDateTextFieldActionPerformed(evt);
            }
        });

        invoiceDueDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        invoiceDueDateLabel.setText(bundle.getString("invoice.duedate")); // NOI18N

        invoiceDueDateTextField.setEditable(false);
        invoiceDueDateTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        invoiceDueDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceDueDateTextFieldActionPerformed(evt);
            }
        });

        discountLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        discountLabel.setText(bundle.getString("invoice.discount")); // NOI18N

        discountTextField.setEditable(false);
        discountTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        discountTextField.setText("0");
        discountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTextFieldActionPerformed(evt);
            }
        });

        netValueTextLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        netValueTextLabel.setText("จำนวนเงิน");

        invoiceDateTextField.setEditable(false);
        invoiceDateTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        netValueTextTextField.setEditable(false);
        netValueTextTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        netValueTextTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netValueTextTextFieldActionPerformed(evt);
            }
        });

        invoiceIdLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        invoiceIdLabel.setText(bundle.getString("invoice.no")); // NOI18N

        invoiceIdTextField.setEditable(false);
        invoiceIdTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(customerIdLabel)
                            .addComponent(customerNameLabel)
                            .addComponent(addressLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(customerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(189, 189, 189)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(invoiceDueDateLabel)
                            .addComponent(paymentDueDateLabel)
                            .addComponent(poNumberLabel)
                            .addComponent(invoiceDateLabel)
                            .addComponent(invoiceIdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(invoiceIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(invoiceDateTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(paymentDueDateTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(invoiceDueDateTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(poNumberTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(invoiceInfoTitleLabel)
                                .addGap(4, 648, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(netValueTextLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(netValueTextTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(netValueLabel))
                                    .addComponent(discountLabel)
                                    .addComponent(totalValueLabel)
                                    .addComponent(vatLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(netValueTextField)
                                    .addComponent(vatTextField)
                                    .addComponent(discountTextField)
                                    .addComponent(totalValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25))))
            .addGroup(layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(cancelButton)
                .addContainerGap(449, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invoiceInfoTitleLabel)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameLabel)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceIdLabel)
                    .addComponent(invoiceIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceDateLabel)
                            .addComponent(invoiceDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(poNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poNumberLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentDueDateLabel)
                            .addComponent(paymentDueDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceDueDateLabel)
                            .addComponent(invoiceDueDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIdLabel)
                    .addComponent(customerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalValueLabel))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netValueLabel)
                    .addComponent(netValueTextLabel)
                    .addComponent(netValueTextTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addGap(116, 116, 116))
        );
    }// </editor-fold>//GEN-END:initComponents

private void customerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_customerNameTextFieldActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    MainFrameAction action = new MainFrameAction();
    action.closeInternalFrame(this.getInternalFrame());
}//GEN-LAST:event_cancelButtonActionPerformed

private void invoiceDetailTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invoiceDetailTableKeyReleased
}//GEN-LAST:event_invoiceDetailTableKeyReleased

private void invoiceDetailTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invoiceDetailTableKeyPressed
}//GEN-LAST:event_invoiceDetailTableKeyPressed

private void invoiceDueDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceDueDateTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_invoiceDueDateTextFieldActionPerformed

private void totalValueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalValueTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_totalValueTextFieldActionPerformed

private void vatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_vatTextFieldActionPerformed

private void discountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_discountTextFieldActionPerformed

private void paymentDueDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentDueDateTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_paymentDueDateTextFieldActionPerformed

private void netValueTextTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netValueTextTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_netValueTextTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel addressLabel;
    protected javax.swing.JTextArea addressTextArea;
    protected javax.swing.JButton cancelButton;
    protected javax.swing.JLabel customerIdLabel;
    protected javax.swing.JTextField customerIdTextField;
    protected javax.swing.JLabel customerNameLabel;
    protected javax.swing.JTextField customerNameTextField;
    protected javax.swing.JLabel discountLabel;
    protected javax.swing.JTextField discountTextField;
    protected javax.swing.JLabel invoiceDateLabel;
    protected javax.swing.JTextField invoiceDateTextField;
    protected javax.swing.JTable invoiceDetailTable;
    protected javax.swing.JLabel invoiceDueDateLabel;
    protected javax.swing.JTextField invoiceDueDateTextField;
    protected javax.swing.JLabel invoiceIdLabel;
    protected javax.swing.JTextField invoiceIdTextField;
    protected javax.swing.JLabel invoiceInfoTitleLabel;
    protected javax.swing.JProgressBar jProgressBar1;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JScrollPane jScrollPane2;
    protected javax.swing.JLabel netValueLabel;
    protected javax.swing.JTextField netValueTextField;
    protected javax.swing.JLabel netValueTextLabel;
    protected javax.swing.JTextField netValueTextTextField;
    protected javax.swing.JLabel paymentDueDateLabel;
    protected javax.swing.JTextField paymentDueDateTextField;
    protected javax.swing.JLabel poNumberLabel;
    protected javax.swing.JTextField poNumberTextField;
    protected javax.swing.JLabel totalValueLabel;
    protected javax.swing.JTextField totalValueTextField;
    protected javax.swing.JLabel vatLabel;
    protected javax.swing.JTextField vatTextField;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JFrame mainFrame;
    private JPanel openerPanel;
    private JInternalFrame internalFrame;
    private InvoiceHead invoiceHead;

    public void assignDefaultValue(InvoiceHead invoiceHead){
        this.getCustomerIdTextField().setText(invoiceHead.getCustomer().getCustomerId());
        this.getCustomerNameTextField().setText(invoiceHead.getCustomer().getCustomerName());
        this.getAddressTextArea().setText(invoiceHead.getCustomer().getCustomerAddres());
        this.getInvoiceIdTextField().setText(invoiceHead.getInvoiceHeadId());
        this.getInvoiceDateTextField().setText(DateUtil.convertDateUtilToDateStr(invoiceHead.getCreateDate()));
        this.getPoNumberTextField().setText(invoiceHead.getPoNumber());
        this.getPaymentDueDateTextField().setText(DateUtil.convertDateUtilToDateStr(invoiceHead.getPaymentDueDate()));
        this.getInvoiceDueDateTextField().setText(DateUtil.convertDateUtilToDateStr(invoiceHead.getInvoiceDueDate()));
        this.getTotalValueTextField().setText(StringUtil.formatThaiCurrency(invoiceHead.getTotalAmount()));
        this.discountTextField.setText(StringUtil.formatThaiCurrency(invoiceHead.getDiscount()));
        this.getVatTextField().setText(StringUtil.formatThaiCurrency(invoiceHead.getVat()));
        this.getNetValueTextField().setText(StringUtil.formatThaiCurrency(invoiceHead.getNetAmount()));
        this.getNetValueTextTextField().setText(invoiceHead.getNetAmountText());
        InvoiceAction action = new InvoiceAction();
        for(InvoiceDetail detail : invoiceHead.getInvoiceDetailSet()){
            action.addInvoiceDetailViewRow(this, detail);
        }
    }
    /**
     * @return the addressLabel
     */
    public javax.swing.JLabel getAddressLabel() {
        return addressLabel;
    }

    /**
     * @param addressLabel the addressLabel to set
     */
    public void setAddressLabel(javax.swing.JLabel addressLabel) {
        this.addressLabel = addressLabel;
    }

    /**
     * @return the addressTextArea
     */
    public javax.swing.JTextArea getAddressTextArea() {
        return addressTextArea;
    }

    /**
     * @param addressTextArea the addressTextArea to set
     */
    public void setAddressTextArea(javax.swing.JTextArea addressTextArea) {
        this.addressTextArea = addressTextArea;
    }

    /**
     * @return the cancelButton
     */
    public javax.swing.JButton getCancelButton() {
        return cancelButton;
    }

    /**
     * @param cancelButton the cancelButton to set
     */
    public void setCancelButton(javax.swing.JButton cancelButton) {
        this.cancelButton = cancelButton;
    }

    /**
     * @return the customerIdLabel
     */
    public javax.swing.JLabel getCustomerIdLabel() {
        return customerIdLabel;
    }

    /**
     * @param customerIdLabel the customerIdLabel to set
     */
    public void setCustomerIdLabel(javax.swing.JLabel customerIdLabel) {
        this.customerIdLabel = customerIdLabel;
    }

    /**
     * @return the customerIdTextField
     */
    public javax.swing.JTextField getCustomerIdTextField() {
        return customerIdTextField;
    }

    /**
     * @param customerIdTextField the customerIdTextField to set
     */
    public void setCustomerIdTextField(javax.swing.JTextField customerIdTextField) {
        this.customerIdTextField = customerIdTextField;
    }

    /**
     * @return the customerNameLabel
     */
    public javax.swing.JLabel getCustomerNameLabel() {
        return customerNameLabel;
    }

    /**
     * @param customerNameLabel the customerNameLabel to set
     */
    public void setCustomerNameLabel(javax.swing.JLabel customerNameLabel) {
        this.customerNameLabel = customerNameLabel;
    }

    /**
     * @return the customerNameTextField
     */
    public javax.swing.JTextField getCustomerNameTextField() {
        return customerNameTextField;
    }

    /**
     * @param customerNameTextField the customerNameTextField to set
     */
    public void setCustomerNameTextField(javax.swing.JTextField customerNameTextField) {
        this.customerNameTextField = customerNameTextField;
    }

    /**
     * @return the discountLabel
     */
    public javax.swing.JLabel getDiscountLabel() {
        return discountLabel;
    }

    /**
     * @param discountLabel the discountLabel to set
     */
    public void setDiscountLabel(javax.swing.JLabel discountLabel) {
        this.discountLabel = discountLabel;
    }

    /**
     * @return the discountTextField
     */
    public javax.swing.JTextField getDiscountTextField() {
        return discountTextField;
    }

    /**
     * @param discountTextField the discountTextField to set
     */
    public void setDiscountTextField(javax.swing.JTextField discountTextField) {
        this.discountTextField = discountTextField;
    }

    /**
     * @return the invoiceDateLabel
     */
    public javax.swing.JLabel getInvoiceDateLabel() {
        return invoiceDateLabel;
    }

    /**
     * @param invoiceDateLabel the invoiceDateLabel to set
     */
    public void setInvoiceDateLabel(javax.swing.JLabel invoiceDateLabel) {
        this.invoiceDateLabel = invoiceDateLabel;
    }

    /**
     * @return the invoiceDateTextField
     */
    public javax.swing.JTextField getInvoiceDateTextField() {
        return invoiceDateTextField;
    }

    /**
     * @param invoiceDateTextField the invoiceDateTextField to set
     */
    public void setInvoiceDateTextField(javax.swing.JTextField invoiceDateTextField) {
        this.invoiceDateTextField = invoiceDateTextField;
    }

    /**
     * @return the invoiceDetailTable
     */
    public javax.swing.JTable getInvoiceDetailTable() {
        return invoiceDetailTable;
    }

    /**
     * @param invoiceDetailTable the invoiceDetailTable to set
     */
    public void setInvoiceDetailTable(javax.swing.JTable invoiceDetailTable) {
        this.invoiceDetailTable = invoiceDetailTable;
    }

    /**
     * @return the invoiceDueDateLabel
     */
    public javax.swing.JLabel getInvoiceDueDateLabel() {
        return invoiceDueDateLabel;
    }

    /**
     * @param invoiceDueDateLabel the invoiceDueDateLabel to set
     */
    public void setInvoiceDueDateLabel(javax.swing.JLabel invoiceDueDateLabel) {
        this.invoiceDueDateLabel = invoiceDueDateLabel;
    }

    /**
     * @return the invoiceDueDateTextField
     */
    public javax.swing.JTextField getInvoiceDueDateTextField() {
        return invoiceDueDateTextField;
    }

    /**
     * @param invoiceDueDateTextField the invoiceDueDateTextField to set
     */
    public void setInvoiceDueDateTextField(javax.swing.JTextField invoiceDueDateTextField) {
        this.invoiceDueDateTextField = invoiceDueDateTextField;
    }

    /**
     * @return the invoiceIdLabel
     */
    public javax.swing.JLabel getInvoiceIdLabel() {
        return invoiceIdLabel;
    }

    /**
     * @param invoiceIdLabel the invoiceIdLabel to set
     */
    public void setInvoiceIdLabel(javax.swing.JLabel invoiceIdLabel) {
        this.invoiceIdLabel = invoiceIdLabel;
    }

    /**
     * @return the invoiceIdTextField
     */
    public javax.swing.JTextField getInvoiceIdTextField() {
        return invoiceIdTextField;
    }

    /**
     * @param invoiceIdTextField the invoiceIdTextField to set
     */
    public void setInvoiceIdTextField(javax.swing.JTextField invoiceIdTextField) {
        this.invoiceIdTextField = invoiceIdTextField;
    }

    /**
     * @return the invoiceInfoTitleLabel
     */
    public javax.swing.JLabel getInvoiceInfoTitleLabel() {
        return invoiceInfoTitleLabel;
    }

    /**
     * @param invoiceInfoTitleLabel the invoiceInfoTitleLabel to set
     */
    public void setInvoiceInfoTitleLabel(javax.swing.JLabel invoiceInfoTitleLabel) {
        this.invoiceInfoTitleLabel = invoiceInfoTitleLabel;
    }

    /**
     * @return the jProgressBar1
     */
    public javax.swing.JProgressBar getjProgressBar1() {
        return jProgressBar1;
    }

    /**
     * @param jProgressBar1 the jProgressBar1 to set
     */
    public void setjProgressBar1(javax.swing.JProgressBar jProgressBar1) {
        this.jProgressBar1 = jProgressBar1;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jScrollPane2
     */
    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * @param jScrollPane2 the jScrollPane2 to set
     */
    public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    /**
     * @return the netValueLabel
     */
    public javax.swing.JLabel getNetValueLabel() {
        return netValueLabel;
    }

    /**
     * @param netValueLabel the netValueLabel to set
     */
    public void setNetValueLabel(javax.swing.JLabel netValueLabel) {
        this.netValueLabel = netValueLabel;
    }

    /**
     * @return the netValueTextField
     */
    public javax.swing.JTextField getNetValueTextField() {
        return netValueTextField;
    }

    /**
     * @param netValueTextField the netValueTextField to set
     */
    public void setNetValueTextField(javax.swing.JTextField netValueTextField) {
        this.netValueTextField = netValueTextField;
    }

    /**
     * @return the netValueTextLabel
     */
    public javax.swing.JLabel getNetValueTextLabel() {
        return netValueTextLabel;
    }

    /**
     * @param netValueTextLabel the netValueTextLabel to set
     */
    public void setNetValueTextLabel(javax.swing.JLabel netValueTextLabel) {
        this.netValueTextLabel = netValueTextLabel;
    }

    /**
     * @return the netValueTextTextField
     */
    public javax.swing.JTextField getNetValueTextTextField() {
        return netValueTextTextField;
    }

    /**
     * @param netValueTextTextField the netValueTextTextField to set
     */
    public void setNetValueTextTextField(javax.swing.JTextField netValueTextTextField) {
        this.netValueTextTextField = netValueTextTextField;
    }

    /**
     * @return the paymentDueDateLabel
     */
    public javax.swing.JLabel getPaymentDueDateLabel() {
        return paymentDueDateLabel;
    }

    /**
     * @param paymentDueDateLabel the paymentDueDateLabel to set
     */
    public void setPaymentDueDateLabel(javax.swing.JLabel paymentDueDateLabel) {
        this.paymentDueDateLabel = paymentDueDateLabel;
    }

    /**
     * @return the paymentDueDateTextField
     */
    public javax.swing.JTextField getPaymentDueDateTextField() {
        return paymentDueDateTextField;
    }

    /**
     * @param paymentDueDateTextField the paymentDueDateTextField to set
     */
    public void setPaymentDueDateTextField(javax.swing.JTextField paymentDueDateTextField) {
        this.paymentDueDateTextField = paymentDueDateTextField;
    }

    /**
     * @return the poNumberLabel
     */
    public javax.swing.JLabel getPoNumberLabel() {
        return poNumberLabel;
    }

    /**
     * @param poNumberLabel the poNumberLabel to set
     */
    public void setPoNumberLabel(javax.swing.JLabel poNumberLabel) {
        this.poNumberLabel = poNumberLabel;
    }

    /**
     * @return the poNumberTextField
     */
    public javax.swing.JTextField getPoNumberTextField() {
        return poNumberTextField;
    }

    /**
     * @param poNumberTextField the poNumberTextField to set
     */
    public void setPoNumberTextField(javax.swing.JTextField poNumberTextField) {
        this.poNumberTextField = poNumberTextField;
    }

    /**
     * @return the totalValueLabel
     */
    public javax.swing.JLabel getTotalValueLabel() {
        return totalValueLabel;
    }

    /**
     * @param totalValueLabel the totalValueLabel to set
     */
    public void setTotalValueLabel(javax.swing.JLabel totalValueLabel) {
        this.totalValueLabel = totalValueLabel;
    }

    /**
     * @return the totalValueTextField
     */
    public javax.swing.JTextField getTotalValueTextField() {
        return totalValueTextField;
    }

    /**
     * @param totalValueTextField the totalValueTextField to set
     */
    public void setTotalValueTextField(javax.swing.JTextField totalValueTextField) {
        this.totalValueTextField = totalValueTextField;
    }

    /**
     * @return the vatLabel
     */
    public javax.swing.JLabel getVatLabel() {
        return vatLabel;
    }

    /**
     * @param vatLabel the vatLabel to set
     */
    public void setVatLabel(javax.swing.JLabel vatLabel) {
        this.vatLabel = vatLabel;
    }

    /**
     * @return the vatTextField
     */
    public javax.swing.JTextField getVatTextField() {
        return vatTextField;
    }

    /**
     * @param vatTextField the vatTextField to set
     */
    public void setVatTextField(javax.swing.JTextField vatTextField) {
        this.vatTextField = vatTextField;
    }

    /**
     * @return the mainFrame
     */
    public javax.swing.JFrame getMainFrame() {
        return mainFrame;
    }

    /**
     * @param mainFrame the mainFrame to set
     */
    public void setMainFrame(javax.swing.JFrame mainFrame) {
        this.mainFrame = mainFrame;
    }

    /**
     * @return the openerPanel
     */
    public JPanel getOpenerPanel() {
        return openerPanel;
    }

    /**
     * @param openerPanel the openerPanel to set
     */
    public void setOpenerPanel(JPanel openerPanel) {
        this.openerPanel = openerPanel;
    }

    /**
     * @return the internalFrame
     */
    public JInternalFrame getInternalFrame() {
        return internalFrame;
    }

    /**
     * @param internalFrame the internalFrame to set
     */
    public void setInternalFrame(JInternalFrame internalFrame) {
        this.internalFrame = internalFrame;
    }

    /**
     * @return the invoiceHead
     */
    public InvoiceHead getInvoiceHead() {
        return invoiceHead;
    }

    /**
     * @param invoiceHead the invoiceHead to set
     */
    public void setInvoiceHead(InvoiceHead invoiceHead) {
        this.invoiceHead = invoiceHead;
    }
    
}