/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InvoiceInfoViewInternalFrame.java
 *
 * Created on Apr 8, 2013, 8:13:53 AM
 */
package com.freebasicacc.ui;

import com.freebasicacc.model.InvoiceHead;
import com.freebasicacc.ui.action.MainFrameAction;
import javax.swing.ImageIcon;

/**
 *
 * @author benzyaa
 */
public class InvoiceInfoViewInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form InvoiceInfoViewInternalFrame */
    public InvoiceInfoViewInternalFrame() {
        initComponents();
        this.SetIcon();
        this.setTitleFont();
    }
    
    public InvoiceInfoViewInternalFrame(InvoiceHead invoiceHead) {
        initComponents();
        this.invoiceInfoPanelView1.setInvoiceHead(invoiceHead);
        this.invoiceInfoPanelView1.assignDefaultValue(invoiceHead);
        this.invoiceInfoPanelView1.setInternalFrame(this);
        this.SetIcon();
        this.setTitleFont();
    }
    
       private void SetIcon(){
        ImageIcon mainIcon = new ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/Document1616.png")); 
        this.setFrameIcon(mainIcon);
    }
    
    private void setTitleFont(){
        MainFrameAction action = new MainFrameAction();
        action.setInternalFramTitle(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invoiceInfoPanelView1 = new com.freebasicacc.ui.InvoiceInfoPanelView();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setResizable(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/freebasicacc/ui/bundle"); // NOI18N
        setTitle(bundle.getString("list.invoice")); // NOI18N
        setPreferredSize(new java.awt.Dimension(886, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invoiceInfoPanelView1, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(invoiceInfoPanelView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected com.freebasicacc.ui.InvoiceInfoPanelView invoiceInfoPanelView1;
    // End of variables declaration//GEN-END:variables
}
