/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Mar 24, 2013, 7:04:37 AM
 */
package com.freebasicacc.ui;

import com.freebasicacc.ui.action.MainFrameAction;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author benzyaa
 */
public class MainFrame extends javax.swing.JFrame {

    private static transient Logger logger = LogManager.getLogger(MainFrame.class);
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        this.setTitle("FreebasicAccountManagement - Version 1.0");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mainFrameDesktopPanel = new javax.swing.JDesktopPane();
        MainMenuBar = new javax.swing.JMenuBar();
        customerMenuItem = new javax.swing.JMenu();
        materialnfoListItem = new javax.swing.JMenu();
        quotationMenuItem = new javax.swing.JMenu();
        invoiceMenuItem = new javax.swing.JMenu();
        settingsMenuItem = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenu();

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText("File");
        jMenu1.setName("jMenu1"); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setName("jMenu2"); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenuBar2.setName("jMenuBar2"); // NOI18N

        jMenu3.setText("File");
        jMenu3.setName("jMenu3"); // NOI18N
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/freebasicacc/ui/bundle"); // NOI18N
        jMenu4.setActionCommand(bundle.getString("MainFrame.jMenu4.actionCommand")); // NOI18N
        jMenu4.setName("jMenu4"); // NOI18N
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        mainFrameDesktopPanel.setName("mainFrameDesktopPanel"); // NOI18N

        MainMenuBar.setName("MainMenuBar"); // NOI18N

        customerMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/Office-Client-Male-Light-icon1616.png"))); // NOI18N
        customerMenuItem.setText(bundle.getString("menu.manage.customer")); // NOI18N
        customerMenuItem.setToolTipText("");
        customerMenuItem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerMenuItem.setName("CUSTOMER_ADD_MENU_ITEM"); // NOI18N
        customerMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerMenuItemMouseClicked(evt);
            }
        });
        customerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerMenuItemActionPerformed(evt);
            }
        });
        MainMenuBar.add(customerMenuItem);

        materialnfoListItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/Misc-Misc-Box-icon1616.png"))); // NOI18N
        materialnfoListItem.setText(bundle.getString("menu.manage.material")); // NOI18N
        materialnfoListItem.setToolTipText("");
        materialnfoListItem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        materialnfoListItem.setName("MATERIAL_LIST_MENU_ITEM"); // NOI18N
        materialnfoListItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialnfoListItemMouseClicked(evt);
            }
        });
        materialnfoListItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialnfoListItemActionPerformed(evt);
            }
        });
        MainMenuBar.add(materialnfoListItem);

        quotationMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/Document1616.png"))); // NOI18N
        quotationMenuItem.setText(bundle.getString("menu.manage.quotation")); // NOI18N
        quotationMenuItem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        quotationMenuItem.setName("quotationMenuItem"); // NOI18N
        quotationMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quotationMenuItemMouseClicked(evt);
            }
        });
        quotationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quotationMenuItemActionPerformed(evt);
            }
        });
        MainMenuBar.add(quotationMenuItem);

        invoiceMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/Document1616.png"))); // NOI18N
        invoiceMenuItem.setText(bundle.getString("menu.manage.invoice")); // NOI18N
        invoiceMenuItem.setToolTipText("");
        invoiceMenuItem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        invoiceMenuItem.setName("INVOICE_ADD_MENU_ITEM"); // NOI18N
        invoiceMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoiceMenuItemMouseClicked(evt);
            }
        });
        invoiceMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceMenuItemActionPerformed(evt);
            }
        });
        MainMenuBar.add(invoiceMenuItem);

        settingsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/tools_1616.png"))); // NOI18N
        settingsMenuItem.setText(bundle.getString("menu.manage.settings")); // NOI18N
        settingsMenuItem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        settingsMenuItem.setName("settingsMenuItem"); // NOI18N
        settingsMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMenuItemMouseClicked(evt);
            }
        });
        MainMenuBar.add(settingsMenuItem);

        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/about_1616.png"))); // NOI18N
        aboutMenuItem.setText(bundle.getString("menu.manage.about")); // NOI18N
        aboutMenuItem.setToolTipText("");
        aboutMenuItem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        aboutMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMenuItemMouseClicked(evt);
            }
        });
        MainMenuBar.add(aboutMenuItem);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrameDesktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrameDesktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public void changeLanguage(String langId){
    Locale.setDefault(new Locale(langId));
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/freebasicacc/ui/bundle");
    customerMenuItem.setText(bundle.getString("menu.manage.customer"));
    materialnfoListItem.setText(bundle.getString("menu.manage.material"));
    quotationMenuItem.setText(bundle.getString("menu.manage.quotation"));
    invoiceMenuItem.setText(bundle.getString("menu.manage.invoice"));
    settingsMenuItem.setText(bundle.getString("menu.manage.settings"));
    aboutMenuItem.setText(bundle.getString("menu.manage.about"));
}
private void customerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerMenuItemActionPerformed

}//GEN-LAST:event_customerMenuItemActionPerformed

private void materialnfoListItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialnfoListItemActionPerformed
    MainFrameAction action = new MainFrameAction();
     action.openInternalFormByType(this, getMaterialnfoListItem());
}//GEN-LAST:event_materialnfoListItemActionPerformed

private void quotationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quotationMenuItemActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_quotationMenuItemActionPerformed

private void invoiceMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceMenuItemActionPerformed
    MainFrameAction action = new MainFrameAction();
    action.openInternalFormByType(this, invoiceMenuItem);
}//GEN-LAST:event_invoiceMenuItemActionPerformed

private void customerMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerMenuItemMouseClicked
     JMenuItem menuItem = new JMenuItem();
     menuItem.setName("CUSTOMER_LIST_MENU_ITEM");
     MainFrameAction action = new MainFrameAction();
     action.openInternalFormByType(this, menuItem);
}//GEN-LAST:event_customerMenuItemMouseClicked

private void materialnfoListItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialnfoListItemMouseClicked
    JMenuItem menuItem = new JMenuItem();
    menuItem.setName("MATERIAL_LIST_MENU_ITEM");
    MainFrameAction action = new MainFrameAction();
    action.openInternalFormByType(this, menuItem);
}//GEN-LAST:event_materialnfoListItemMouseClicked

private void quotationMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quotationMenuItemMouseClicked
     JMenuItem menuItem = new JMenuItem();
    menuItem.setName("QUOTATION_LIST_MENU_ITEM");
    MainFrameAction action = new MainFrameAction();
    action.openInternalFormByType(this, menuItem);
}//GEN-LAST:event_quotationMenuItemMouseClicked

private void invoiceMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceMenuItemMouseClicked
    JMenuItem menuItem = new JMenuItem();
    menuItem.setName("INVOICE_LIST_MENU_ITEM");
    MainFrameAction action = new MainFrameAction();
    action.openInternalFormByType(this, menuItem);
}//GEN-LAST:event_invoiceMenuItemMouseClicked

    private void settingsMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMenuItemMouseClicked
         logger.info("Setting Menu Clicked");
            JMenuItem menuItem = new JMenuItem();
            menuItem.setName("SETTINGS_MENU_ITEM");
            MainFrameAction action = new MainFrameAction();
            action.openInternalFormByType(this, menuItem);
    }//GEN-LAST:event_settingsMenuItemMouseClicked

    private void aboutMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMenuItemMouseClicked
         logger.info("About Menu Clicked");
         JMenuItem menuItem = new JMenuItem();
         menuItem.setName("ABOUT_MENU_ITEM");
         MainFrameAction action = new MainFrameAction();
         action.openInternalFormByType(this, menuItem);
    }//GEN-LAST:event_aboutMenuItemMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JMenu aboutMenuItem;
    private javax.swing.JMenu customerMenuItem;
    private javax.swing.JMenu invoiceMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JDesktopPane mainFrameDesktopPanel;
    private javax.swing.JMenu materialnfoListItem;
    private javax.swing.JMenu quotationMenuItem;
    private javax.swing.JMenu settingsMenuItem;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the AddcustomerMenu
     */
    

    /**
     * @return the MainMenuBar
     */
    public javax.swing.JMenuBar getMainMenuBar() {
        return MainMenuBar;
    }

    /**
     * @param MainMenuBar the MainMenuBar to set
     */
    public void setMainMenuBar(javax.swing.JMenuBar MainMenuBar) {
        this.MainMenuBar = MainMenuBar;
    }
    /**
     * @return the customerMenuItem
     */
    public javax.swing.JMenu getCustomerMenuItem() {
        return customerMenuItem;
    }

    /**
     * @param customerMenuItem the customerMenuItem to set
     */
    public void setCustomerMenuItem(javax.swing.JMenu customerMenuItem) {
        this.customerMenuItem = customerMenuItem;
    }

    /**
     * @return the invoiceMenuItem
     */
    public javax.swing.JMenu getInvoiceMenuItem() {
        return invoiceMenuItem;
    }

    /**
     * @param invoiceMenuItem the invoiceMenuItem to set
     */
    public void setInvoiceMenuItem(javax.swing.JMenu invoiceMenuItem) {
        this.invoiceMenuItem = invoiceMenuItem;
    }
    
    /**
     * @return the mainFrameDesktopPanel
     */
    public javax.swing.JDesktopPane getMainFrameDesktopPanel() {
        return mainFrameDesktopPanel;
    }

    /**
     * @param mainFrameDesktopPanel the mainFrameDesktopPanel to set
     */
    public void setMainFrameDesktopPanel(javax.swing.JDesktopPane mainFrameDesktopPanel) {
        this.mainFrameDesktopPanel = mainFrameDesktopPanel;
    }

    /**
     * @return the materialMenuItem
     */
   

    /**
     * @return the quotationMenuItem
     */
    public javax.swing.JMenu getQuotationMenuItem() {
        return quotationMenuItem;
    }

    /**
     * @param quotationMenuItem the quotationMenuItem to set
     */
    public void setQuotationMenuItem(javax.swing.JMenu quotationMenuItem) {
        this.quotationMenuItem = quotationMenuItem;
    }

    

    /**
     * @return the materialAddInfoItem
     */
    public javax.swing.JMenu getMaterialAddInfoItem() {
        return getMaterialnfoListItem();
    }

    /**
     * @return the materialAddMenuItem
     */
    

    /**
     * @param materialAddMenuItem the materialAddMenuItem to set
     */
    

    /**
     * @return the materialnfoListItem
     */
    public javax.swing.JMenu getMaterialnfoListItem() {
        return materialnfoListItem;
    }

    /**
     * @param materialnfoListItem the materialnfoListItem to set
     */
    public void setMaterialnfoListItem(javax.swing.JMenu materialnfoListItem) {
        this.materialnfoListItem = materialnfoListItem;
    }
    
}
