/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MaterialInfoPanel.java
 *
 * Created on Mar 28, 2013, 9:57:23 PM
 */
package com.freebasicacc.ui;

import com.freebasicacc.action.MaterialAction;
import com.freebasicacc.model.Material;
import com.freebasicacc.model.Unit;
import com.freebasicacc.ui.action.MainFrameAction;
import com.freebasicacc.ui.listener.BannedKeyListener;
import com.freebasicacc.ui.listener.LimitLengthListener;
import com.freebasicacc.util.StringUtil;
import javax.swing.JComboBox;

/**
 *
 * @author benzyaa
 */
public class MaterialInfoPanelEdit extends javax.swing.JPanel {

    /** Creates new form MaterialInfoPanel */
    public MaterialInfoPanelEdit() {
        initComponents();
        MaterialAction action = new MaterialAction();
        action.assignUnitCombobox(junitComboBox,this.selectedUnitId, null);
        this.materialDescriptionTextArea.addKeyListener(new LimitLengthListener(200));
        this.materialNameTextField.addKeyListener(new LimitLengthListener(40));
        this.materialPriceTextField.addKeyListener(new LimitLengthListener(10));
        this.materialPriceTextField.addKeyListener(new BannedKeyListener("CURRENCY"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialInfoLabel = new javax.swing.JLabel();
        maierialNameLabel = new javax.swing.JLabel();
        materialDescriptionLabel = new javax.swing.JLabel();
        materialPriceLabel = new javax.swing.JLabel();
        materialUnitLabel = new javax.swing.JLabel();
        materialNameTextField = new javax.swing.JTextField();
        materialPriceTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        materialDescriptionTextArea = new javax.swing.JTextArea();
        junitComboBox = new javax.swing.JComboBox();
        saveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        materialIdLabel = new javax.swing.JLabel();
        materialIdValue = new javax.swing.JLabel();

        materialInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        materialInfoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/Misc-Misc-Box-icon.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/freebasicacc/ui/bundle"); // NOI18N
        materialInfoLabel.setText(bundle.getString("dialog.meterial.edit")); // NOI18N

        maierialNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maierialNameLabel.setText(bundle.getString("material.name")); // NOI18N

        materialDescriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        materialDescriptionLabel.setText(bundle.getString("material.description")); // NOI18N

        materialPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        materialPriceLabel.setText(bundle.getString("material.price")); // NOI18N

        materialUnitLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        materialUnitLabel.setText(bundle.getString("material.unit")); // NOI18N

        materialNameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        materialNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialNameTextFieldActionPerformed(evt);
            }
        });

        materialPriceTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        materialPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialPriceTextFieldActionPerformed(evt);
            }
        });
        materialPriceTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                materialPriceTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                materialPriceTextFieldFocusLost(evt);
            }
        });

        materialDescriptionTextArea.setColumns(20);
        materialDescriptionTextArea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        materialDescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(materialDescriptionTextArea);

        junitComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        junitComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                junitComboBoxActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/22.png"))); // NOI18N
        saveButton.setText(bundle.getString("common.save")); // NOI18N
        saveButton.setActionCommand(bundle.getString("common.save")); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/45.png"))); // NOI18N
        clearButton.setText(bundle.getString("common.reset")); // NOI18N
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/33.png"))); // NOI18N
        cancelButton.setText(bundle.getString("common.cancel")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        materialIdLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        materialIdLabel.setText(bundle.getString("material.code")); // NOI18N

        materialIdValue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        materialIdValue.setText("material id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maierialNameLabel)
                            .addComponent(materialPriceLabel)
                            .addComponent(materialUnitLabel)
                            .addComponent(materialDescriptionLabel)
                            .addComponent(materialInfoLabel)
                            .addComponent(materialIdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(materialNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(materialPriceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(junitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(materialIdValue)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(materialInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materialIdLabel)
                    .addComponent(materialIdValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maierialNameLabel)
                    .addComponent(materialNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materialPriceLabel)
                    .addComponent(materialPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materialUnitLabel)
                    .addComponent(junitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(materialDescriptionLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(clearButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void materialNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialNameTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_materialNameTextFieldActionPerformed

private void materialPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialPriceTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_materialPriceTextFieldActionPerformed

private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    MaterialAction action = new MaterialAction();
    action.updateMaterialAction(this);
    action.searchMaterialAction((MaterialInFoListPanel)this.openerPanel, true);
}//GEN-LAST:event_saveButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    MainFrameAction action = new MainFrameAction();
    action.closeInternalFrame(this.getInternalFrame());
}//GEN-LAST:event_cancelButtonActionPerformed

private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
    System.out.println("SelectedUnitId=>"+this.getJunitComboBox().getName());
    this.assignDefaultValue(material);
}//GEN-LAST:event_clearButtonActionPerformed

private void junitComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_junitComboBoxActionPerformed
    JComboBox combobox = (JComboBox)evt.getSource();// TODO add your handling code here:
    Unit unit = (Unit)combobox.getSelectedItem();
    System.out.println("unit id =>"+unit.getUnitId());
}//GEN-LAST:event_junitComboBoxActionPerformed

private void materialPriceTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_materialPriceTextFieldFocusGained
    MainFrameAction action = new MainFrameAction();
    action.assignNumberToTextFieldByCurrency(this.getMaterialPriceTextField());
}//GEN-LAST:event_materialPriceTextFieldFocusGained

private void materialPriceTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_materialPriceTextFieldFocusLost
    MainFrameAction action = new MainFrameAction();
    action.assignCurrencyTextToNumberByCurrency(this.getMaterialPriceTextField());
}//GEN-LAST:event_materialPriceTextFieldFocusLost

public void assignDefaultValue(Material material){
        this.getJunitComboBox().getModel().setSelectedItem(material.getUnit());
        this.getMaterialDescriptionTextArea().setText(material.getMaterialDesc());
        this.getMaterialNameTextField().setText(material.getMaterialName());
        this.getMaterialPriceTextField().setText(StringUtil.formatThaiCurrency(material.getMaterialPrice()));
        this.getMaterialIdValue().setText(material.getMaterialId());
}

private void displayComboBoxDropDownList(JComboBox combobox){
  //  combobox.getModel().
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox junitComboBox;
    private javax.swing.JLabel maierialNameLabel;
    private javax.swing.JLabel materialDescriptionLabel;
    private javax.swing.JTextArea materialDescriptionTextArea;
    private javax.swing.JLabel materialIdLabel;
    private javax.swing.JLabel materialIdValue;
    private javax.swing.JLabel materialInfoLabel;
    private javax.swing.JTextField materialNameTextField;
    private javax.swing.JLabel materialPriceLabel;
    private javax.swing.JTextField materialPriceTextField;
    private javax.swing.JLabel materialUnitLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JPanel openerPanel;
    private javax.swing.JInternalFrame internalFrame;
    private String selectedUnitId;
    private Material material;

    /**
     * @return the cancelButton
     */
    public javax.swing.JButton getCancelButton() {
        return cancelButton;
    }

    /**
     * @param cancelButton the cancelButton to set
     */
    public void setCancelButton(javax.swing.JButton cancelButton) {
        this.cancelButton = cancelButton;
    }

    /**
     * @return the clearButton
     */
    public javax.swing.JButton getClearButton() {
        return clearButton;
    }

    /**
     * @param clearButton the clearButton to set
     */
    public void setClearButton(javax.swing.JButton clearButton) {
        this.clearButton = clearButton;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the junitComboBox
     */
    public javax.swing.JComboBox getJunitComboBox() {
        return junitComboBox;
    }

    /**
     * @param junitComboBox the junitComboBox to set
     */
    public void setJunitComboBox(javax.swing.JComboBox junitComboBox) {
        this.junitComboBox = junitComboBox;
    }

    /**
     * @return the maierialNameLabel
     */
    public javax.swing.JLabel getMaierialNameLabel() {
        return maierialNameLabel;
    }

    /**
     * @param maierialNameLabel the maierialNameLabel to set
     */
    public void setMaierialNameLabel(javax.swing.JLabel maierialNameLabel) {
        this.maierialNameLabel = maierialNameLabel;
    }

    /**
     * @return the materialDescriptionLabel
     */
    public javax.swing.JLabel getMaterialDescriptionLabel() {
        return materialDescriptionLabel;
    }

    /**
     * @param materialDescriptionLabel the materialDescriptionLabel to set
     */
    public void setMaterialDescriptionLabel(javax.swing.JLabel materialDescriptionLabel) {
        this.materialDescriptionLabel = materialDescriptionLabel;
    }

    /**
     * @return the materialDescriptionTextArea
     */
    public javax.swing.JTextArea getMaterialDescriptionTextArea() {
        return materialDescriptionTextArea;
    }

    /**
     * @param materialDescriptionTextArea the materialDescriptionTextArea to set
     */
    public void setMaterialDescriptionTextArea(javax.swing.JTextArea materialDescriptionTextArea) {
        this.materialDescriptionTextArea = materialDescriptionTextArea;
    }

    /**
     * @return the materialInfoLabel
     */
    public javax.swing.JLabel getMaterialInfoLabel() {
        return materialInfoLabel;
    }

    /**
     * @param materialInfoLabel the materialInfoLabel to set
     */
    public void setMaterialInfoLabel(javax.swing.JLabel materialInfoLabel) {
        this.materialInfoLabel = materialInfoLabel;
    }

    /**
     * @return the materialNameTextField
     */
    public javax.swing.JTextField getMaterialNameTextField() {
        return materialNameTextField;
    }

    /**
     * @param materialNameTextField the materialNameTextField to set
     */
    public void setMaterialNameTextField(javax.swing.JTextField materialNameTextField) {
        this.materialNameTextField = materialNameTextField;
    }

    /**
     * @return the materialPriceLabel
     */
    public javax.swing.JLabel getMaterialPriceLabel() {
        return materialPriceLabel;
    }

    /**
     * @param materialPriceLabel the materialPriceLabel to set
     */
    public void setMaterialPriceLabel(javax.swing.JLabel materialPriceLabel) {
        this.materialPriceLabel = materialPriceLabel;
    }

    /**
     * @return the materialPriceTextField
     */
    public javax.swing.JTextField getMaterialPriceTextField() {
        return materialPriceTextField;
    }

    /**
     * @param materialPriceTextField the materialPriceTextField to set
     */
    public void setMaterialPriceTextField(javax.swing.JTextField materialPriceTextField) {
        this.materialPriceTextField = materialPriceTextField;
    }

    /**
     * @return the materialUnitLabel
     */
    public javax.swing.JLabel getMaterialUnitLabel() {
        return materialUnitLabel;
    }

    /**
     * @param materialUnitLabel the materialUnitLabel to set
     */
    public void setMaterialUnitLabel(javax.swing.JLabel materialUnitLabel) {
        this.materialUnitLabel = materialUnitLabel;
    }

    /**
     * @return the saveButton
     */
    public javax.swing.JButton getSaveButton() {
        return saveButton;
    }

    /**
     * @param saveButton the saveButton to set
     */
    public void setSaveButton(javax.swing.JButton saveButton) {
        this.saveButton = saveButton;
    }

    /**
     * @return the openerPanel
     */
    public javax.swing.JPanel getOpenerPanel() {
        return openerPanel;
    }

    /**
     * @param openerPanel the openerPanel to set
     */
    public void setOpenerPanel(javax.swing.JPanel openerPanel) {
        this.openerPanel = openerPanel;
    }

    /**
     * @return the internalFrame
     */
    public javax.swing.JInternalFrame getInternalFrame() {
        return internalFrame;
    }

    /**
     * @param internalFrame the internalFrame to set
     */
    public void setInternalFrame(javax.swing.JInternalFrame internalFrame) {
        this.internalFrame = internalFrame;
    }

    /**
     * @return the selectedUnitId
     */
    public String getSelectedUnitId() {
        return selectedUnitId;
    }

    /**
     * @param selectedUnitId the selectedUnitId to set
     */
    public void setSelectedUnitId(String selectedUnitId) {
        this.selectedUnitId = selectedUnitId;
    }

    /**
     * @return the material
     */
    public Material getMaterial() {
        return material;
    }

    /**
     * @param material the material to set
     */
    public void setMaterial(Material material) {
        this.material = material;
    }

    /**
     * @return the materialIdValue
     */
    public javax.swing.JLabel getMaterialIdValue() {
        return materialIdValue;
    }

    /**
     * @param materialIdValue the materialIdValue to set
     */
    public void setMaterialIdValue(javax.swing.JLabel materialIdValue) {
        this.materialIdValue = materialIdValue;
    }
    
}