/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QuotationInfoPanel.java
 *
 * Created on Apr 6, 2013, 10:45:15 AM
 */
package com.freebasicacc.ui;

import com.freebasicacc.action.QuotationAction;
import com.freebasicacc.ui.action.MainFrameAction;
import com.freebasicacc.ui.listener.BannedKeyListener;
import com.freebasicacc.ui.listener.LimitLengthListener;
import com.freebasicacc.ui.listener.QuotationDetailListTableListener;
import com.freebasicacc.util.MessageUtil;
import com.freebasicacc.util.UIUtil;
import javax.swing.JInternalFrame;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author benzyaa
 */
public class QuotationInfoPanel extends javax.swing.JPanel {

    /** Creates new form QuotationInfoPanel */
    public QuotationInfoPanel() {
        initComponents();
        customerIdHiddenValueLabel.setVisible(false);
        QuotationDetailListTableListener tableListener = new QuotationDetailListTableListener();
        tableListener.setHandlerPanel(this);
        this.quotationDetailTable.getTableHeader().setFont(new java.awt.Font("Tahoma", 0, 12));
        this.quotationDetailTable.getModel().addTableModelListener(tableListener);
        this.leadTimeTextField.addKeyListener(new LimitLengthListener(10));
        this.paymentTermTextField.addKeyListener(new LimitLengthListener(50));
        this.quotationTitleTextField.addKeyListener(new LimitLengthListener(200));
        this.leadTimeTextField.addKeyListener(new BannedKeyListener("DATE"));
    }

    public javax.swing.table.DefaultTableModel generateModelForColumn(){
        return new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                    MessageUtil.getMessage("common.sequence"), 
                    MessageUtil.getMessage("common.list"),
                    MessageUtil.getMessage("common.quantity"),
                    MessageUtil.getMessage("quotation.material.unit"),
                    MessageUtil.getMessage("quotation.material.priceperunit"),   
                    MessageUtil.getMessage("quotation.material.amountvalue")
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        quotationInfoTitleLabel = new javax.swing.JLabel();
        quotationTitleLabel = new javax.swing.JLabel();
        quotationTitleTextField = new javax.swing.JTextField();
        customerContractLabel = new javax.swing.JLabel();
        customerContractTextField = new javax.swing.JTextField();
        customerNameLabel = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        paymentTermLabel = new javax.swing.JLabel();
        paymentTermTextField = new javax.swing.JTextField();
        customerDialogOpenButton = new javax.swing.JButton();
        phoneLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        deliveryplaceLabel = new javax.swing.JLabel();
        deliveryPlaceTextField = new javax.swing.JTextField();
        leadTimeLabel = new javax.swing.JLabel();
        leadTimeTextField = new javax.swing.JTextField();
        leadDatePicker = new javax.swing.JButton();
        addDetailButton = new javax.swing.JButton();
        removeDetailButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        quotationDetailTable = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        totalValueTextField = new javax.swing.JTextField();
        vatTextField = new javax.swing.JTextField();
        netValueTextField = new javax.swing.JTextField();
        totalValueLabel = new javax.swing.JLabel();
        vatLabel = new javax.swing.JLabel();
        netValueLabel = new javax.swing.JLabel();
        customerIdHiddenValueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        quotationInfoTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quotationInfoTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/Document.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/freebasicacc/ui/bundle"); // NOI18N
        quotationInfoTitleLabel.setText(bundle.getString("dialog.invoice.title.create")); // NOI18N

        quotationTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        quotationTitleLabel.setText(bundle.getString("quotation.title")); // NOI18N

        quotationTitleTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        quotationTitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quotationTitleTextFieldActionPerformed(evt);
            }
        });

        customerContractLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerContractLabel.setText(bundle.getString("quotation.dear")); // NOI18N

        customerContractTextField.setEditable(false);
        customerContractTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        customerNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerNameLabel.setText(bundle.getString("quotation.customer")); // NOI18N

        customerNameTextField.setEditable(false);
        customerNameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTextFieldActionPerformed(evt);
            }
        });

        paymentTermLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paymentTermLabel.setText(bundle.getString("quotation.paymentterm")); // NOI18N

        paymentTermTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paymentTermTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTermTextFieldActionPerformed(evt);
            }
        });

        customerDialogOpenButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerDialogOpenButton.setText("...");
        customerDialogOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerDialogOpenButtonActionPerformed(evt);
            }
        });

        phoneLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        phoneLabel.setText(bundle.getString("customer.phone")); // NOI18N

        phoneTextField.setEditable(false);
        phoneTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        deliveryplaceLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deliveryplaceLabel.setText(bundle.getString("quotation.deliveryplace")); // NOI18N

        deliveryPlaceTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deliveryPlaceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryPlaceTextFieldActionPerformed(evt);
            }
        });

        leadTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        leadTimeLabel.setText(bundle.getString("quotation.leaddate")); // NOI18N

        leadTimeTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        leadDatePicker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/43.png"))); // NOI18N
        leadDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leadDatePickerActionPerformed(evt);
            }
        });

        addDetailButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addDetailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/13.png"))); // NOI18N
        addDetailButton.setText(bundle.getString("common.add")); // NOI18N
        addDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDetailButtonActionPerformed(evt);
            }
        });

        removeDetailButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        removeDetailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/14.png"))); // NOI18N
        removeDetailButton.setText(bundle.getString("common.remove")); // NOI18N
        removeDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDetailButtonActionPerformed(evt);
            }
        });

        quotationDetailTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        quotationDetailTable.setModel(this.generateModelForColumn());
        quotationDetailTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quotationDetailTableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quotationDetailTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(quotationDetailTable);

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/22.png"))); // NOI18N
        saveButton.setText(bundle.getString("common.save")); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/45.png"))); // NOI18N
        clearButton.setText(bundle.getString("common.clear")); // NOI18N
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/33.png"))); // NOI18N
        cancelButton.setText(bundle.getString("common.cancel")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        totalValueTextField.setEditable(false);
        totalValueTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalValueTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalValueTextField.setText("0.00");

        vatTextField.setEditable(false);
        vatTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vatTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vatTextField.setText("0.00");

        netValueTextField.setEditable(false);
        netValueTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        netValueTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        netValueTextField.setText("0.00");

        totalValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalValueLabel.setText(bundle.getString("quotation.totalvalue")); // NOI18N

        vatLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vatLabel.setText(bundle.getString("quotation.valueaddedtax")); // NOI18N

        netValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        netValueLabel.setText(bundle.getString("quotation.netvalue")); // NOI18N

        customerIdHiddenValueLabel.setText("jLabel1");

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(quotationInfoTitleLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(quotationTitleLabel)
                                .addGap(18, 18, 18)
                                .addComponent(quotationTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(customerIdHiddenValueLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(addDetailButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeDetailButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(phoneLabel)
                                    .addComponent(customerNameLabel)
                                    .addComponent(customerContractLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(customerNameTextField)
                                            .addComponent(customerContractTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                                        .addGap(2, 2, 2)
                                        .addComponent(customerDialogOpenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(deliveryplaceLabel)
                                            .addComponent(paymentTermLabel)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                        .addComponent(leadTimeLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(leadTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(leadDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(paymentTermTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(deliveryPlaceTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(506, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalValueLabel)
                            .addComponent(vatLabel)
                            .addComponent(netValueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vatTextField)
                            .addComponent(totalValueTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(netValueTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quotationInfoTitleLabel)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quotationTitleLabel)
                    .addComponent(jLabel1)
                    .addComponent(quotationTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerContractTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentTermLabel)
                    .addComponent(paymentTermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(customerContractLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(customerNameLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customerDialogOpenButton)
                        .addComponent(deliveryplaceLabel)
                        .addComponent(deliveryPlaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leadTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leadTimeLabel)))
                    .addComponent(leadDatePicker)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerIdHiddenValueLabel)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDetailButton)
                    .addComponent(removeDetailButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(clearButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void quotationTitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quotationTitleTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_quotationTitleTextFieldActionPerformed

private void customerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_customerNameTextFieldActionPerformed

private void customerDialogOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerDialogOpenButtonActionPerformed
    MainFrameAction action = new MainFrameAction();
    JMenuItem menuItem = new JMenuItem();
    menuItem.setName("CUSTOMER_DIALOG_MENU_ITEM");
    action.openInternalFormByType((MainFrame)this.mainFrame, menuItem,this,null);
}//GEN-LAST:event_customerDialogOpenButtonActionPerformed

private void paymentTermTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTermTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_paymentTermTextFieldActionPerformed

private void deliveryPlaceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryPlaceTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_deliveryPlaceTextFieldActionPerformed

private void leadDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leadDatePickerActionPerformed
        UIUtil util = new UIUtil();
        util.openDatepickerForTextField(this.leadTimeTextField,this.getMainFrame());
}//GEN-LAST:event_leadDatePickerActionPerformed

private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        this.assignDefaultValue();
}//GEN-LAST:event_clearButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
     MainFrameAction action = new MainFrameAction();
     action.closeInternalFrame(this.internalFrame);
}//GEN-LAST:event_cancelButtonActionPerformed

private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    QuotationAction action = new QuotationAction();
    action.saveQuotationAction(this);
}//GEN-LAST:event_saveButtonActionPerformed

private void removeDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDetailButtonActionPerformed
    QuotationAction action = new QuotationAction();
    action.removeQuotationRow(this);
}//GEN-LAST:event_removeDetailButtonActionPerformed

private void addDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDetailButtonActionPerformed
        MainFrameAction action = new MainFrameAction();
        JMenuItem menuItem = new JMenuItem();
        menuItem.setName("MATERIAL_DIALOG_MENU_ITEM");
        action.openInternalFormByType((MainFrame)this.getMainFrame(), menuItem, this, null);
       
}//GEN-LAST:event_addDetailButtonActionPerformed

private void quotationDetailTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quotationDetailTableKeyReleased
 
}//GEN-LAST:event_quotationDetailTableKeyReleased

private void quotationDetailTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quotationDetailTableKeyPressed
 
}//GEN-LAST:event_quotationDetailTableKeyPressed

private void assignDefaultValue(){
     this.quotationTitleTextField.setText("");
     this.customerNameTextField.setText("");
     this.customerIdHiddenValueLabel.setText("");
     this.customerContractTextField.setText("");
     this.phoneTextField.setText("");
     this.paymentTermTextField.setText("");
     this.deliveryPlaceTextField.setText("");
     this.leadTimeTextField.setText("");
     this.totalValueTextField.setText("0.00");
     this.vatTextField.setText("0.00");
     this.netValueTextField.setText("0.00");
     MainFrameAction action = new MainFrameAction();
     action.removeAllTableRow(quotationDetailTable);
     
} 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton addDetailButton;
    protected javax.swing.JButton cancelButton;
    protected javax.swing.JButton clearButton;
    protected javax.swing.JLabel customerContractLabel;
    protected javax.swing.JTextField customerContractTextField;
    protected javax.swing.JButton customerDialogOpenButton;
    protected javax.swing.JLabel customerIdHiddenValueLabel;
    protected javax.swing.JLabel customerNameLabel;
    protected javax.swing.JTextField customerNameTextField;
    protected javax.swing.JTextField deliveryPlaceTextField;
    protected javax.swing.JLabel deliveryplaceLabel;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JLabel jLabel4;
    protected javax.swing.JLabel jLabel5;
    protected javax.swing.JLabel jLabel6;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JButton leadDatePicker;
    protected javax.swing.JLabel leadTimeLabel;
    protected javax.swing.JTextField leadTimeTextField;
    protected javax.swing.JLabel netValueLabel;
    protected javax.swing.JTextField netValueTextField;
    protected javax.swing.JLabel paymentTermLabel;
    protected javax.swing.JTextField paymentTermTextField;
    protected javax.swing.JLabel phoneLabel;
    protected javax.swing.JTextField phoneTextField;
    protected javax.swing.JTable quotationDetailTable;
    protected javax.swing.JLabel quotationInfoTitleLabel;
    protected javax.swing.JLabel quotationTitleLabel;
    protected javax.swing.JTextField quotationTitleTextField;
    protected javax.swing.JButton removeDetailButton;
    protected javax.swing.JButton saveButton;
    protected javax.swing.JLabel totalValueLabel;
    protected javax.swing.JTextField totalValueTextField;
    protected javax.swing.JLabel vatLabel;
    protected javax.swing.JTextField vatTextField;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JFrame mainFrame;
    private JPanel openerPanel;
    private JInternalFrame internalFrame;
    
    
    
    /**
     * @return the addDetailButton
     */
    public javax.swing.JButton getAddDetailButton() {
        return addDetailButton;
    }

    /**
     * @param addDetailButton the addDetailButton to set
     */
    public void setAddDetailButton(javax.swing.JButton addDetailButton) {
        this.addDetailButton = addDetailButton;
    }

    /**
     * @return the cancelButton
     */
    public javax.swing.JButton getCancelButton() {
        return cancelButton;
    }

    /**
     * @param cancelButton the cancelButton to set
     */
    public void setCancelButton(javax.swing.JButton cancelButton) {
        this.cancelButton = cancelButton;
    }

    /**
     * @return the clearButton
     */
    public javax.swing.JButton getClearButton() {
        return clearButton;
    }

    /**
     * @param clearButton the clearButton to set
     */
    public void setClearButton(javax.swing.JButton clearButton) {
        this.clearButton = clearButton;
    }

    /**
     * @return the customerContractLabel
     */
    public javax.swing.JLabel getCustomerContractLabel() {
        return customerContractLabel;
    }

    /**
     * @param customerContractLabel the customerContractLabel to set
     */
    public void setCustomerContractLabel(javax.swing.JLabel customerContractLabel) {
        this.customerContractLabel = customerContractLabel;
    }

    /**
     * @return the customerContractTextField
     */
    public javax.swing.JTextField getCustomerContractTextField() {
        return customerContractTextField;
    }

    /**
     * @param customerContractTextField the customerContractTextField to set
     */
    public void setCustomerContractTextField(javax.swing.JTextField customerContractTextField) {
        this.customerContractTextField = customerContractTextField;
    }

    /**
     * @return the customerNameLabel
     */
    public javax.swing.JLabel getCustomerNameLabel() {
        return customerNameLabel;
    }

    /**
     * @param customerNameLabel the customerNameLabel to set
     */
    public void setCustomerNameLabel(javax.swing.JLabel customerNameLabel) {
        this.customerNameLabel = customerNameLabel;
    }

    /**
     * @return the customerNameTextField
     */
    public javax.swing.JTextField getCustomerNameTextField() {
        return customerNameTextField;
    }

    /**
     * @param customerNameTextField the customerNameTextField to set
     */
    public void setCustomerNameTextField(javax.swing.JTextField customerNameTextField) {
        this.customerNameTextField = customerNameTextField;
    }

    /**
     * @return the deliveryPlaceTextField
     */
    public javax.swing.JTextField getDeliveryPlaceTextField() {
        return deliveryPlaceTextField;
    }

    /**
     * @param deliveryPlaceTextField the deliveryPlaceTextField to set
     */
    public void setDeliveryPlaceTextField(javax.swing.JTextField deliveryPlaceTextField) {
        this.deliveryPlaceTextField = deliveryPlaceTextField;
    }

    /**
     * @return the deliveryplaceLabel
     */
    public javax.swing.JLabel getDeliveryplaceLabel() {
        return deliveryplaceLabel;
    }

    /**
     * @param deliveryplaceLabel the deliveryplaceLabel to set
     */
    public void setDeliveryplaceLabel(javax.swing.JLabel deliveryplaceLabel) {
        this.deliveryplaceLabel = deliveryplaceLabel;
    }

    /**
     * @return the jButton1
     */
    public javax.swing.JButton getjButton1() {
        return customerDialogOpenButton;
    }

    /**
     * @param jButton1 the jButton1 to set
     */
    public void setjButton1(javax.swing.JButton jButton1) {
        this.customerDialogOpenButton = jButton1;
    }

    /**
     * @return the jButton2
     */
    public javax.swing.JButton getjButton2() {
        return leadDatePicker;
    }

    /**
     * @param jButton2 the jButton2 to set
     */
    public void setjButton2(javax.swing.JButton jButton2) {
        this.leadDatePicker = jButton2;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the leadTimeLabel
     */
    public javax.swing.JLabel getLeadTimeLabel() {
        return leadTimeLabel;
    }

    /**
     * @param leadTimeLabel the leadTimeLabel to set
     */
    public void setLeadTimeLabel(javax.swing.JLabel leadTimeLabel) {
        this.leadTimeLabel = leadTimeLabel;
    }

    /**
     * @return the leadTimeTextField
     */
    public javax.swing.JTextField getLeadTimeTextField() {
        return leadTimeTextField;
    }

    /**
     * @param leadTimeTextField the leadTimeTextField to set
     */
    public void setLeadTimeTextField(javax.swing.JTextField leadTimeTextField) {
        this.leadTimeTextField = leadTimeTextField;
    }

    /**
     * @return the netValueLabel
     */
    public javax.swing.JLabel getNetValueLabel() {
        return netValueLabel;
    }

    /**
     * @param netValueLabel the netValueLabel to set
     */
    public void setNetValueLabel(javax.swing.JLabel netValueLabel) {
        this.netValueLabel = netValueLabel;
    }

    /**
     * @return the netValueTextField
     */
    public javax.swing.JTextField getNetValueTextField() {
        return netValueTextField;
    }

    /**
     * @param netValueTextField the netValueTextField to set
     */
    public void setNetValueTextField(javax.swing.JTextField netValueTextField) {
        this.netValueTextField = netValueTextField;
    }

    /**
     * @return the paymentTermLabel
     */
    public javax.swing.JLabel getPaymentTermLabel() {
        return paymentTermLabel;
    }

    /**
     * @param paymentTermLabel the paymentTermLabel to set
     */
    public void setPaymentTermLabel(javax.swing.JLabel paymentTermLabel) {
        this.paymentTermLabel = paymentTermLabel;
    }

    /**
     * @return the paymentTermTextField
     */
    public javax.swing.JTextField getPaymentTermTextField() {
        return paymentTermTextField;
    }

    /**
     * @param paymentTermTextField the paymentTermTextField to set
     */
    public void setPaymentTermTextField(javax.swing.JTextField paymentTermTextField) {
        this.paymentTermTextField = paymentTermTextField;
    }

    /**
     * @return the phoneLabel
     */
    public javax.swing.JLabel getPhoneLabel() {
        return phoneLabel;
    }

    /**
     * @param phoneLabel the phoneLabel to set
     */
    public void setPhoneLabel(javax.swing.JLabel phoneLabel) {
        this.phoneLabel = phoneLabel;
    }

    /**
     * @return the phoneTextField
     */
    public javax.swing.JTextField getPhoneTextField() {
        return phoneTextField;
    }

    /**
     * @param phoneTextField the phoneTextField to set
     */
    public void setPhoneTextField(javax.swing.JTextField phoneTextField) {
        this.phoneTextField = phoneTextField;
    }

    /**
     * @return the quotationDetailTable
     */
    public javax.swing.JTable getQuotationDetailTable() {
        return quotationDetailTable;
    }

    /**
     * @param quotationDetailTable the quotationDetailTable to set
     */
    public void setQuotationDetailTable(javax.swing.JTable quotationDetailTable) {
        this.quotationDetailTable = quotationDetailTable;
    }

    
    /**
     * @return the quotationInfoTitleLabel
     */
    public javax.swing.JLabel getQuotationInfoTitleLabel() {
        return quotationInfoTitleLabel;
    }

    /**
     * @param quotationInfoTitleLabel the quotationInfoTitleLabel to set
     */
    public void setQuotationInfoTitleLabel(javax.swing.JLabel quotationInfoTitleLabel) {
        this.quotationInfoTitleLabel = quotationInfoTitleLabel;
    }

    /**
     * @return the quotationTitleLabel
     */
    public javax.swing.JLabel getQuotationTitleLabel() {
        return quotationTitleLabel;
    }

    /**
     * @param quotationTitleLabel the quotationTitleLabel to set
     */
    public void setQuotationTitleLabel(javax.swing.JLabel quotationTitleLabel) {
        this.quotationTitleLabel = quotationTitleLabel;
    }

    /**
     * @return the quotationTitleTextField
     */
    public javax.swing.JTextField getQuotationTitleTextField() {
        return quotationTitleTextField;
    }

    /**
     * @param quotationTitleTextField the quotationTitleTextField to set
     */
    public void setQuotationTitleTextField(javax.swing.JTextField quotationTitleTextField) {
        this.quotationTitleTextField = quotationTitleTextField;
    }

    /**
     * @return the removeDetailButton
     */
    public javax.swing.JButton getRemoveDetailButton() {
        return removeDetailButton;
    }

    /**
     * @param removeDetailButton the removeDetailButton to set
     */
    public void setRemoveDetailButton(javax.swing.JButton removeDetailButton) {
        this.removeDetailButton = removeDetailButton;
    }

    /**
     * @return the saveButton
     */
    public javax.swing.JButton getSaveButton() {
        return saveButton;
    }

    /**
     * @param saveButton the saveButton to set
     */
    public void setSaveButton(javax.swing.JButton saveButton) {
        this.saveButton = saveButton;
    }

    /**
     * @return the totalValueLabel
     */
    public javax.swing.JLabel getTotalValueLabel() {
        return totalValueLabel;
    }

    /**
     * @param totalValueLabel the totalValueLabel to set
     */
    public void setTotalValueLabel(javax.swing.JLabel totalValueLabel) {
        this.totalValueLabel = totalValueLabel;
    }

    /**
     * @return the totalValueTextField
     */
    public javax.swing.JTextField getTotalValueTextField() {
        return totalValueTextField;
    }

    /**
     * @param totalValueTextField the totalValueTextField to set
     */
    public void setTotalValueTextField(javax.swing.JTextField totalValueTextField) {
        this.totalValueTextField = totalValueTextField;
    }

    /**
     * @return the vatLabel
     */
    public javax.swing.JLabel getVatLabel() {
        return vatLabel;
    }

    /**
     * @param vatLabel the vatLabel to set
     */
    public void setVatLabel(javax.swing.JLabel vatLabel) {
        this.vatLabel = vatLabel;
    }

    /**
     * @return the vatTextField
     */
    public javax.swing.JTextField getVatTextField() {
        return vatTextField;
    }

    /**
     * @param vatTextField the vatTextField to set
     */
    public void setVatTextField(javax.swing.JTextField vatTextField) {
        this.vatTextField = vatTextField;
    }

    /**
     * @return the mainFrame
     */
    public javax.swing.JFrame getMainFrame() {
        return mainFrame;
    }

    /**
     * @param mainFrame the mainFrame to set
     */
    public void setMainFrame(javax.swing.JFrame mainFrame) {
        this.mainFrame = mainFrame;
    }

    /**
     * @return the customerIdHiddenValueLabel
     */
    public javax.swing.JLabel getCustomerIdHiddenValueLabel() {
        return customerIdHiddenValueLabel;
    }

    /**
     * @param customerIdHiddenValueLabel the customerIdHiddenValueLabel to set
     */
    public void setCustomerIdHiddenValueLabel(javax.swing.JLabel customerIdHiddenValueLabel) {
        this.customerIdHiddenValueLabel = customerIdHiddenValueLabel;
    }

    /**
     * @return the internalFrame
     */
    public JInternalFrame getInternalFrame() {
        return internalFrame;
    }

    /**
     * @param internalFrame the internalFrame to set
     */
    public void setInternalFrame(JInternalFrame internalFrame) {
        this.internalFrame = internalFrame;
    }

    /**
     * @return the openerPanel
     */
    public JPanel getOpenerPanel() {
        return openerPanel;
    }

    /**
     * @param openerPanel the openerPanel to set
     */
    public void setOpenerPanel(JPanel openerPanel) {
        this.openerPanel = openerPanel;
    }
    
    
}