/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QuotationInfoInternalFrame.java
 *
 * Created on Apr 6, 2013, 11:27:20 AM
 */
package com.freebasicacc.ui;

import com.freebasicacc.ui.action.MainFrameAction;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author benzyaa
 */
public class QuotationInfoInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form QuotationInfoInternalFrame */
    public QuotationInfoInternalFrame() {
        initComponents();
        this.SetIcon();
        this.setTitleFont();
    }
    
    public QuotationInfoInternalFrame(JFrame mainFrame) {
        initComponents();
        this.quotationInfoPanel2.setMainFrame(mainFrame);
        this.quotationInfoPanel2.setInternalFrame(this);
        this.SetIcon();
        this.setTitleFont();
    }
    
    
    public QuotationInfoInternalFrame(JFrame mainFrame,JPanel openerPanel) {
        initComponents();
        this.quotationInfoPanel2.setMainFrame(mainFrame);
        this.quotationInfoPanel2.setInternalFrame(this);
        this.quotationInfoPanel2.setOpenerPanel(openerPanel);
        this.SetIcon();
        this.setTitleFont();
    }
    
      
     private void SetIcon(){
        ImageIcon mainIcon = new ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/Document1616.png")); 
        this.setFrameIcon(mainIcon);
    }
    
    private void setTitleFont(){
        MainFrameAction action = new MainFrameAction();
        action.setInternalFramTitle(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quotationInfoPanel1 = new com.freebasicacc.ui.QuotationInfoPanel();
        quotationInfoPanel2 = new com.freebasicacc.ui.QuotationInfoPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setResizable(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/freebasicacc/ui/bundle"); // NOI18N
        setTitle(bundle.getString("dialog.quotation.title.create")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quotationInfoPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quotationInfoPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected com.freebasicacc.ui.QuotationInfoPanel quotationInfoPanel1;
    protected com.freebasicacc.ui.QuotationInfoPanel quotationInfoPanel2;
    // End of variables declaration//GEN-END:variables
}
