/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UnitListInternalFrame.java
 *
 * Created on Mar 31, 2013, 10:10:32 AM
 */
package com.freebasicacc.ui;

import com.freebasicacc.ui.action.MainFrameAction;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author benzyaa
 */
public class UnitListInternalFrame extends javax.swing.JInternalFrame {

    private static UnitListInternalFrame unitListInternalFrameInstance;
    /** Creates new form UnitListInternalFrame */
    private UnitListInternalFrame() {
        initComponents();
        this.SetIcon();
        this.setTitleFont();
    }
    
    private UnitListInternalFrame(JFrame frame) {
        initComponents();
        this.unitListPanel1.setMainFrame(frame);
        this.SetIcon();
        this.setTitleFont();
    }
    
    public UnitListInternalFrame getInstances(){
        return getInstances(null);
    }
    
    public static UnitListInternalFrame getInstances(JFrame frame){
        if(unitListInternalFrameInstance == null)unitListInternalFrameInstance = new UnitListInternalFrame(frame);
        return UnitListInternalFrame.unitListInternalFrameInstance;
    }
    

    private void SetIcon(){
        ImageIcon mainIcon = new ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/shopping_cart_16x16.png")); 
        this.setFrameIcon(mainIcon);
    }
    
    private void setTitleFont(){
        MainFrameAction action = new MainFrameAction();
        action.setInternalFramTitle(this);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unitListPanel1 = new com.freebasicacc.ui.UnitListPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/freebasicacc/ui/bundle"); // NOI18N
        setTitle(bundle.getString("dialog.unit.title.manage")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(unitListPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(unitListPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.freebasicacc.ui.UnitListPanel unitListPanel1;
    // End of variables declaration//GEN-END:variables
}