/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UnitAddPanel.java
 *
 * Created on Mar 31, 2013, 11:44:36 AM
 */
package com.freebasicacc.ui;

import com.freebasicacc.action.UnitAction;
import com.freebasicacc.model.Unit;
import com.freebasicacc.ui.action.MainFrameAction;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author benzyaa
 */
public class UnitEditPanel extends javax.swing.JPanel {

    /** Creates new form UnitAddPanel */
    public UnitEditPanel() {
        initComponents();
    }
    
     
    
    public void setDefaultValue(Unit unit){
        this.getUnitIdValueLabel().setText(unit.getUnitId());
        this.UnitNameTextField.setText(unit.getUnitName());
        this.UnitDescTextField.setText(unit.getUnitDesc());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addUnitLabel = new javax.swing.JLabel();
        unitNameLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        UnitNameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        UnitDescTextField = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        UnitIdLabel = new javax.swing.JLabel();
        UnitIdValueLabel = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        addUnitLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addUnitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/shopping_cart_16x16.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/freebasicacc/ui/bundle"); // NOI18N
        addUnitLabel.setText(bundle.getString("dialog.unit.title.edit")); // NOI18N

        unitNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        unitNameLabel.setText(bundle.getString("unit.name")); // NOI18N

        descriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descriptionLabel.setText(bundle.getString("unit.description")); // NOI18N

        UnitNameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        UnitDescTextField.setColumns(20);
        UnitDescTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UnitDescTextField.setRows(5);
        jScrollPane1.setViewportView(UnitDescTextField);

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/22.png"))); // NOI18N
        saveButton.setText(bundle.getString("common.save")); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/33.png"))); // NOI18N
        cancelButton.setText(bundle.getString("common.cancel")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        UnitIdLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UnitIdLabel.setText(bundle.getString("unit.code")); // NOI18N

        UnitIdValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UnitIdValueLabel.setText("jLabel1");

        clearButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebasicacc/ui/image/45.png"))); // NOI18N
        clearButton.setText(bundle.getString("common.reset")); // NOI18N
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addUnitLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descriptionLabel)
                            .addComponent(UnitIdLabel)
                            .addComponent(saveButton)
                            .addComponent(unitNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UnitIdValueLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clearButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UnitNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addUnitLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnitIdLabel)
                    .addComponent(UnitIdValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnitNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitNameLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton)
                            .addComponent(clearButton)
                            .addComponent(cancelButton)))
                    .addComponent(descriptionLabel))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        UnitAction action = new UnitAction();
        action.updateUnitAction(this);
}//GEN-LAST:event_saveButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        UnitAction action = new UnitAction();
        action.closeUnitDetailFrame(internalFrame);
}//GEN-LAST:event_cancelButtonActionPerformed

private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        this.setDefaultValue(unit);
}//GEN-LAST:event_clearButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea UnitDescTextField;
    private javax.swing.JLabel UnitIdLabel;
    private javax.swing.JLabel UnitIdValueLabel;
    private javax.swing.JTextField UnitNameTextField;
    private javax.swing.JLabel addUnitLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel unitNameLabel;
    // End of variables declaration//GEN-END:variables
    private JPanel openerPanel;
    private JInternalFrame internalFrame;
    private Unit unit;

    /**
     * @return the openerPanel
     */
    public JPanel getOpenerPanel() {
        return openerPanel;
    }

    /**
     * @param openerPanel the openerPanel to set
     */
    public void setOpenerPanel(JPanel openerPanel) {
        this.openerPanel = openerPanel;
    }

    /**
     * @return the UnitDescLabel
     */
    
    /**
     * @return the UnitNameTextField
     */
    public javax.swing.JTextField getUnitNameTextField() {
        return UnitNameTextField;
    }

    /**
     * @param UnitNameTextField the UnitNameTextField to set
     */
    public void setUnitNameTextField(javax.swing.JTextField UnitNameTextField) {
        this.UnitNameTextField = UnitNameTextField;
    }

    /**
     * @return the addUnitLabel
     */
    public javax.swing.JLabel getAddUnitLabel() {
        return addUnitLabel;
    }

    /**
     * @param addUnitLabel the addUnitLabel to set
     */
    public void setAddUnitLabel(javax.swing.JLabel addUnitLabel) {
        this.addUnitLabel = addUnitLabel;
    }

    /**
     * @return the cancelButton
     */
    public javax.swing.JButton getCancelButton() {
        return cancelButton;
    }

    /**
     * @param cancelButton the cancelButton to set
     */
    public void setCancelButton(javax.swing.JButton cancelButton) {
        this.cancelButton = cancelButton;
    }

    /**
     * @return the descriptionLabel
     */
    public javax.swing.JLabel getDescriptionLabel() {
        return descriptionLabel;
    }

    /**
     * @param descriptionLabel the descriptionLabel to set
     */
    public void setDescriptionLabel(javax.swing.JLabel descriptionLabel) {
        this.descriptionLabel = descriptionLabel;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the saveButton
     */
    public javax.swing.JButton getSaveButton() {
        return saveButton;
    }

    /**
     * @param saveButton the saveButton to set
     */
    public void setSaveButton(javax.swing.JButton saveButton) {
        this.saveButton = saveButton;
    }

    /**
     * @return the unitNameLabel
     */
    public javax.swing.JLabel getUnitNameLabel() {
        return unitNameLabel;
    }

    /**
     * @param unitNameLabel the unitNameLabel to set
     */
    public void setUnitNameLabel(javax.swing.JLabel unitNameLabel) {
        this.unitNameLabel = unitNameLabel;
    }

    /**
     * @return the UnitDescTextField
     */
    public javax.swing.JTextArea getUnitDescTextField() {
        return UnitDescTextField;
    }

    /**
     * @param UnitDescTextField the UnitDescTextField to set
     */
    public void setUnitDescTextField(javax.swing.JTextArea UnitDescTextField) {
        this.UnitDescTextField = UnitDescTextField;
    }

    /**
     * @return the internalFrame
     */
    public JInternalFrame getInternalFrame() {
        return internalFrame;
    }

    /**
     * @param internalFrame the internalFrame to set
     */
    public void setInternalFrame(JInternalFrame internalFrame) {
        this.internalFrame = internalFrame;
    }

    /**
     * @return the unit
     */
    public Unit getUnit() {
        return unit;
    }

    /**
     * @param unit the unit to set
     */
    public void setUnit(Unit unit) {
        this.unit = unit;
    }

    /**
     * @return the UnitIdValueLabel
     */
    public javax.swing.JLabel getUnitIdValueLabel() {
        return UnitIdValueLabel;
    }

    /**
     * @param UnitIdValueLabel the UnitIdValueLabel to set
     */
    public void setUnitIdValueLabel(javax.swing.JLabel UnitIdValueLabel) {
        this.UnitIdValueLabel = UnitIdValueLabel;
    }
    
    
}